# ####################################################################

#  Created by Genus(TM) Synthesis Solution 20.11-s111_1 on Wed Jul 23 13:57:44 IST 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design Top

create_clock -name "clk" -period 100.0 -waveform {0.0 50.0} [get_ports clk_pad]
set_clock_transition -min 12.5 [get_clocks clk]
set_clock_transition -max 20.0 [get_clocks clk]
set_load -pin_load 5.0 [get_ports {cipher_pad[3]}]
set_load -pin_load 5.0 [get_ports {cipher_pad[2]}]
set_load -pin_load 5.0 [get_ports {cipher_pad[1]}]
set_load -pin_load 5.0 [get_ports {cipher_pad[0]}]
set_load -pin_load 5.0 [get_ports done_final_pad]
set_load -pin_load 5.0 [get_ports {out_txt_pad[3]}]
set_load -pin_load 5.0 [get_ports {out_txt_pad[2]}]
set_load -pin_load 5.0 [get_ports {out_txt_pad[1]}]
set_load -pin_load 5.0 [get_ports {out_txt_pad[0]}]
set_load -pin_load 5.0 [get_ports {test_pad[5]}]
set_load -pin_load 5.0 [get_ports {test_pad[4]}]
set_load -pin_load 5.0 [get_ports {test_pad[3]}]
set_load -pin_load 5.0 [get_ports {test_pad[2]}]
set_load -pin_load 5.0 [get_ports {test_pad[1]}]
set_load -pin_load 5.0 [get_ports {test_pad[0]}]
set_load -pin_load 5.0 [get_ports txt_done_final_pad]
set_false_path -from [list \
  [get_ports reset_pad]  \
  [get_ports start_pad] ] -to [list \
  [get_cells {u_input_checker/buffer_reg_reg[31]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[30]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[29]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[28]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[27]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[26]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[25]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[24]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[23]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[22]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[21]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[20]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[19]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[18]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[17]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[16]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[15]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[14]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[13]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[12]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[11]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[10]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[9]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[8]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[7]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[6]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[4]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[3]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[2]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[1]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[0]}]  \
  [get_cells {u_input_checker/i_cur_reg[5]}]  \
  [get_cells {u_input_checker/i_cur_reg[4]}]  \
  [get_cells {u_input_checker/i_cur_reg[3]}]  \
  [get_cells {u_input_checker/i_cur_reg[2]}]  \
  [get_cells u_input_checker/done_reg]  \
  [get_cells {u_input_checker/cipher_reg[3]}]  \
  [get_cells {u_input_checker/cipher_reg[2]}]  \
  [get_cells {u_input_checker/cipher_reg[1]}]  \
  [get_cells {u_input_checker/cipher_reg[0]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[31]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[30]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[29]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[28]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[27]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[26]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[25]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[24]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[23]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[22]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[21]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[20]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[19]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[18]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[17]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[16]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[15]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[14]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[13]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[12]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[11]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[10]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[9]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[8]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[7]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[6]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[4]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[3]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[2]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[1]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[0]}]  \
  [get_cells {u_output_giver/i_cur_reg[5]}]  \
  [get_cells {u_output_giver/i_cur_reg[4]}]  \
  [get_cells {u_output_giver/i_cur_reg[3]}]  \
  [get_cells {u_output_giver/i_cur_reg[2]}]  \
  [get_cells u_output_giver/done_reg]  \
  [get_cells {u_output_giver/cipher_reg[3]}]  \
  [get_cells {u_output_giver/cipher_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[1]}]  \
  [get_cells {u_output_giver/cipher_reg[0]}]  \
  [get_cells {u_simon/j_cur_reg[2]}]  \
  [get_cells {u_simon/j_cur_reg[1]}]  \
  [get_cells {u_simon/j_cur_reg[0]}]  \
  [get_cells u_simon/buffer_reg]  \
  [get_cells u_simon/start_prev_reg]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[0]}]  \
  [get_cells u_input_taker/start_buf_reg]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[3]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[2]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[1]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[0]}]  \
  [get_cells {u_input_taker/key_buf_reg[7]}]  \
  [get_cells {u_input_taker/key_buf_reg[6]}]  \
  [get_cells {u_input_taker/key_buf_reg[5]}]  \
  [get_cells {u_input_taker/key_buf_reg[4]}]  \
  [get_cells {u_input_taker/key_buf_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[2]}]  \
  [get_cells {u_input_taker/key_buf_reg[1]}]  \
  [get_cells {u_input_taker/key_buf_reg[0]}]  \
  [get_cells {u_input_taker/state_reg[3]}]  \
  [get_cells {u_input_taker/state_reg[2]}]  \
  [get_cells {u_input_taker/state_reg[1]}]  \
  [get_cells {u_input_taker/state_reg[0]}]  \
  [get_cells u_input_taker/done_reg]  \
  [get_cells {u_input_taker/key_out_reg[63]}]  \
  [get_cells {u_input_taker/key_out_reg[62]}]  \
  [get_cells {u_input_taker/key_out_reg[61]}]  \
  [get_cells {u_input_taker/key_out_reg[60]}]  \
  [get_cells {u_input_taker/key_out_reg[59]}]  \
  [get_cells {u_input_taker/key_out_reg[58]}]  \
  [get_cells {u_input_taker/key_out_reg[57]}]  \
  [get_cells {u_input_taker/key_out_reg[56]}]  \
  [get_cells {u_input_taker/key_out_reg[55]}]  \
  [get_cells {u_input_taker/key_out_reg[54]}]  \
  [get_cells {u_input_taker/key_out_reg[53]}]  \
  [get_cells {u_input_taker/key_out_reg[52]}]  \
  [get_cells {u_input_taker/key_out_reg[51]}]  \
  [get_cells {u_input_taker/key_out_reg[50]}]  \
  [get_cells {u_input_taker/key_out_reg[49]}]  \
  [get_cells {u_input_taker/key_out_reg[48]}]  \
  [get_cells {u_input_taker/key_out_reg[47]}]  \
  [get_cells {u_input_taker/key_out_reg[46]}]  \
  [get_cells {u_input_taker/key_out_reg[45]}]  \
  [get_cells {u_input_taker/key_out_reg[44]}]  \
  [get_cells {u_input_taker/key_out_reg[43]}]  \
  [get_cells {u_input_taker/key_out_reg[42]}]  \
  [get_cells {u_input_taker/key_out_reg[41]}]  \
  [get_cells {u_input_taker/key_out_reg[40]}]  \
  [get_cells {u_input_taker/key_out_reg[39]}]  \
  [get_cells {u_input_taker/key_out_reg[38]}]  \
  [get_cells {u_input_taker/key_out_reg[37]}]  \
  [get_cells {u_input_taker/key_out_reg[36]}]  \
  [get_cells {u_input_taker/key_out_reg[35]}]  \
  [get_cells {u_input_taker/key_out_reg[34]}]  \
  [get_cells {u_input_taker/key_out_reg[33]}]  \
  [get_cells {u_input_taker/key_out_reg[32]}]  \
  [get_cells {u_input_taker/key_out_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[30]}]  \
  [get_cells {u_input_taker/key_out_reg[29]}]  \
  [get_cells {u_input_taker/key_out_reg[28]}]  \
  [get_cells {u_input_taker/key_out_reg[27]}]  \
  [get_cells {u_input_taker/key_out_reg[26]}]  \
  [get_cells {u_input_taker/key_out_reg[25]}]  \
  [get_cells {u_input_taker/key_out_reg[24]}]  \
  [get_cells {u_input_taker/key_out_reg[23]}]  \
  [get_cells {u_input_taker/key_out_reg[22]}]  \
  [get_cells {u_input_taker/key_out_reg[21]}]  \
  [get_cells {u_input_taker/key_out_reg[20]}]  \
  [get_cells {u_input_taker/key_out_reg[19]}]  \
  [get_cells {u_input_taker/key_out_reg[18]}]  \
  [get_cells {u_input_taker/key_out_reg[17]}]  \
  [get_cells {u_input_taker/key_out_reg[16]}]  \
  [get_cells {u_input_taker/key_out_reg[15]}]  \
  [get_cells {u_input_taker/key_out_reg[14]}]  \
  [get_cells {u_input_taker/key_out_reg[13]}]  \
  [get_cells {u_input_taker/key_out_reg[12]}]  \
  [get_cells {u_input_taker/key_out_reg[11]}]  \
  [get_cells {u_input_taker/key_out_reg[10]}]  \
  [get_cells {u_input_taker/key_out_reg[9]}]  \
  [get_cells {u_input_taker/key_out_reg[8]}]  \
  [get_cells {u_input_taker/key_out_reg[7]}]  \
  [get_cells {u_input_taker/key_out_reg[6]}]  \
  [get_cells {u_input_taker/key_out_reg[5]}]  \
  [get_cells {u_input_taker/key_out_reg[4]}]  \
  [get_cells {u_input_taker/key_out_reg[3]}]  \
  [get_cells {u_input_taker/key_out_reg[2]}]  \
  [get_cells {u_input_taker/key_out_reg[1]}]  \
  [get_cells {u_input_taker/key_out_reg[0]}]  \
  [get_cells {u_input_taker/data_reg[31]}]  \
  [get_cells {u_input_taker/data_reg[30]}]  \
  [get_cells {u_input_taker/data_reg[29]}]  \
  [get_cells {u_input_taker/data_reg[28]}]  \
  [get_cells {u_input_taker/data_reg[27]}]  \
  [get_cells {u_input_taker/data_reg[26]}]  \
  [get_cells {u_input_taker/data_reg[25]}]  \
  [get_cells {u_input_taker/data_reg[24]}]  \
  [get_cells {u_input_taker/data_reg[23]}]  \
  [get_cells {u_input_taker/data_reg[22]}]  \
  [get_cells {u_input_taker/data_reg[21]}]  \
  [get_cells {u_input_taker/data_reg[20]}]  \
  [get_cells {u_input_taker/data_reg[19]}]  \
  [get_cells {u_input_taker/data_reg[18]}]  \
  [get_cells {u_input_taker/data_reg[17]}]  \
  [get_cells {u_input_taker/data_reg[16]}]  \
  [get_cells {u_input_taker/data_reg[15]}]  \
  [get_cells {u_input_taker/data_reg[14]}]  \
  [get_cells {u_input_taker/data_reg[13]}]  \
  [get_cells {u_input_taker/data_reg[12]}]  \
  [get_cells {u_input_taker/data_reg[11]}]  \
  [get_cells {u_input_taker/data_reg[10]}]  \
  [get_cells {u_input_taker/data_reg[9]}]  \
  [get_cells {u_input_taker/data_reg[8]}]  \
  [get_cells {u_input_taker/data_reg[7]}]  \
  [get_cells {u_input_taker/data_reg[6]}]  \
  [get_cells {u_input_taker/data_reg[5]}]  \
  [get_cells {u_input_taker/data_reg[4]}]  \
  [get_cells {u_input_taker/data_reg[3]}]  \
  [get_cells {u_input_taker/data_reg[2]}]  \
  [get_cells {u_input_taker/data_reg[1]}]  \
  [get_cells {u_input_taker/data_reg[0]}] ]
group_path -weight 1.000000 -name I2R -from [list \
  [get_ports clk_pad]  \
  [get_ports reset_pad]  \
  [get_ports {key_pad[7]}]  \
  [get_ports {key_pad[6]}]  \
  [get_ports {key_pad[5]}]  \
  [get_ports {key_pad[4]}]  \
  [get_ports {key_pad[3]}]  \
  [get_ports {key_pad[2]}]  \
  [get_ports {key_pad[1]}]  \
  [get_ports {key_pad[0]}]  \
  [get_ports {Plaintxt_pad[3]}]  \
  [get_ports {Plaintxt_pad[2]}]  \
  [get_ports {Plaintxt_pad[1]}]  \
  [get_ports {Plaintxt_pad[0]}]  \
  [get_ports start_pad] ] -to [list \
  [get_cells {u_input_taker/data_reg[0]}]  \
  [get_cells {u_input_taker/data_reg[1]}]  \
  [get_cells {u_input_taker/data_reg[2]}]  \
  [get_cells {u_input_taker/data_reg[3]}]  \
  [get_cells {u_input_taker/data_reg[4]}]  \
  [get_cells {u_input_taker/data_reg[5]}]  \
  [get_cells {u_input_taker/data_reg[6]}]  \
  [get_cells {u_input_taker/data_reg[7]}]  \
  [get_cells {u_input_taker/data_reg[8]}]  \
  [get_cells {u_input_taker/data_reg[9]}]  \
  [get_cells {u_input_taker/data_reg[10]}]  \
  [get_cells {u_input_taker/data_reg[11]}]  \
  [get_cells {u_input_taker/data_reg[12]}]  \
  [get_cells {u_input_taker/data_reg[13]}]  \
  [get_cells {u_input_taker/data_reg[14]}]  \
  [get_cells {u_input_taker/data_reg[15]}]  \
  [get_cells {u_input_taker/data_reg[16]}]  \
  [get_cells {u_input_taker/data_reg[17]}]  \
  [get_cells {u_input_taker/data_reg[18]}]  \
  [get_cells {u_input_taker/data_reg[19]}]  \
  [get_cells {u_input_taker/data_reg[20]}]  \
  [get_cells {u_input_taker/data_reg[21]}]  \
  [get_cells {u_input_taker/data_reg[22]}]  \
  [get_cells {u_input_taker/data_reg[23]}]  \
  [get_cells {u_input_taker/data_reg[24]}]  \
  [get_cells {u_input_taker/data_reg[25]}]  \
  [get_cells {u_input_taker/data_reg[26]}]  \
  [get_cells {u_input_taker/data_reg[27]}]  \
  [get_cells {u_input_taker/data_reg[28]}]  \
  [get_cells {u_input_taker/data_reg[29]}]  \
  [get_cells {u_input_taker/data_reg[30]}]  \
  [get_cells {u_input_taker/data_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[0]}]  \
  [get_cells {u_input_taker/key_out_reg[1]}]  \
  [get_cells {u_input_taker/key_out_reg[2]}]  \
  [get_cells {u_input_taker/key_out_reg[3]}]  \
  [get_cells {u_input_taker/key_out_reg[4]}]  \
  [get_cells {u_input_taker/key_out_reg[5]}]  \
  [get_cells {u_input_taker/key_out_reg[6]}]  \
  [get_cells {u_input_taker/key_out_reg[7]}]  \
  [get_cells {u_input_taker/key_out_reg[8]}]  \
  [get_cells {u_input_taker/key_out_reg[9]}]  \
  [get_cells {u_input_taker/key_out_reg[10]}]  \
  [get_cells {u_input_taker/key_out_reg[11]}]  \
  [get_cells {u_input_taker/key_out_reg[12]}]  \
  [get_cells {u_input_taker/key_out_reg[13]}]  \
  [get_cells {u_input_taker/key_out_reg[14]}]  \
  [get_cells {u_input_taker/key_out_reg[15]}]  \
  [get_cells {u_input_taker/key_out_reg[16]}]  \
  [get_cells {u_input_taker/key_out_reg[17]}]  \
  [get_cells {u_input_taker/key_out_reg[18]}]  \
  [get_cells {u_input_taker/key_out_reg[19]}]  \
  [get_cells {u_input_taker/key_out_reg[20]}]  \
  [get_cells {u_input_taker/key_out_reg[21]}]  \
  [get_cells {u_input_taker/key_out_reg[22]}]  \
  [get_cells {u_input_taker/key_out_reg[23]}]  \
  [get_cells {u_input_taker/key_out_reg[24]}]  \
  [get_cells {u_input_taker/key_out_reg[25]}]  \
  [get_cells {u_input_taker/key_out_reg[26]}]  \
  [get_cells {u_input_taker/key_out_reg[27]}]  \
  [get_cells {u_input_taker/key_out_reg[28]}]  \
  [get_cells {u_input_taker/key_out_reg[29]}]  \
  [get_cells {u_input_taker/key_out_reg[30]}]  \
  [get_cells {u_input_taker/key_out_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[32]}]  \
  [get_cells {u_input_taker/key_out_reg[33]}]  \
  [get_cells {u_input_taker/key_out_reg[34]}]  \
  [get_cells {u_input_taker/key_out_reg[35]}]  \
  [get_cells {u_input_taker/key_out_reg[36]}]  \
  [get_cells {u_input_taker/key_out_reg[37]}]  \
  [get_cells {u_input_taker/key_out_reg[38]}]  \
  [get_cells {u_input_taker/key_out_reg[39]}]  \
  [get_cells {u_input_taker/key_out_reg[40]}]  \
  [get_cells {u_input_taker/key_out_reg[41]}]  \
  [get_cells {u_input_taker/key_out_reg[42]}]  \
  [get_cells {u_input_taker/key_out_reg[43]}]  \
  [get_cells {u_input_taker/key_out_reg[44]}]  \
  [get_cells {u_input_taker/key_out_reg[45]}]  \
  [get_cells {u_input_taker/key_out_reg[46]}]  \
  [get_cells {u_input_taker/key_out_reg[47]}]  \
  [get_cells {u_input_taker/key_out_reg[48]}]  \
  [get_cells {u_input_taker/key_out_reg[49]}]  \
  [get_cells {u_input_taker/key_out_reg[50]}]  \
  [get_cells {u_input_taker/key_out_reg[51]}]  \
  [get_cells {u_input_taker/key_out_reg[52]}]  \
  [get_cells {u_input_taker/key_out_reg[53]}]  \
  [get_cells {u_input_taker/key_out_reg[54]}]  \
  [get_cells {u_input_taker/key_out_reg[55]}]  \
  [get_cells {u_input_taker/key_out_reg[56]}]  \
  [get_cells {u_input_taker/key_out_reg[57]}]  \
  [get_cells {u_input_taker/key_out_reg[58]}]  \
  [get_cells {u_input_taker/key_out_reg[59]}]  \
  [get_cells {u_input_taker/key_out_reg[60]}]  \
  [get_cells {u_input_taker/key_out_reg[61]}]  \
  [get_cells {u_input_taker/key_out_reg[62]}]  \
  [get_cells {u_input_taker/key_out_reg[63]}]  \
  [get_cells u_input_taker/done_reg]  \
  [get_cells {u_input_taker/state_reg[0]}]  \
  [get_cells {u_input_taker/state_reg[1]}]  \
  [get_cells {u_input_taker/state_reg[2]}]  \
  [get_cells {u_input_taker/state_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[0]}]  \
  [get_cells {u_input_taker/key_buf_reg[1]}]  \
  [get_cells {u_input_taker/key_buf_reg[2]}]  \
  [get_cells {u_input_taker/key_buf_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[4]}]  \
  [get_cells {u_input_taker/key_buf_reg[5]}]  \
  [get_cells {u_input_taker/key_buf_reg[6]}]  \
  [get_cells {u_input_taker/key_buf_reg[7]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[0]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[1]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[2]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[3]}]  \
  [get_cells u_input_taker/start_buf_reg]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[15]}]  \
  [get_cells u_simon/start_prev_reg]  \
  [get_cells u_simon/buffer_reg]  \
  [get_cells {u_simon/j_cur_reg[0]}]  \
  [get_cells {u_simon/j_cur_reg[1]}]  \
  [get_cells {u_simon/j_cur_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[0]}]  \
  [get_cells {u_output_giver/cipher_reg[1]}]  \
  [get_cells {u_output_giver/cipher_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[3]}]  \
  [get_cells u_output_giver/done_reg]  \
  [get_cells {u_output_giver/i_cur_reg[2]}]  \
  [get_cells {u_output_giver/i_cur_reg[3]}]  \
  [get_cells {u_output_giver/i_cur_reg[4]}]  \
  [get_cells {u_output_giver/i_cur_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[0]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[1]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[2]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[3]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[4]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[6]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[7]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[8]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[9]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[10]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[11]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[12]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[13]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[14]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[15]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[16]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[17]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[18]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[19]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[20]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[21]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[22]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[23]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[24]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[25]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[26]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[27]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[28]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[29]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[30]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[31]}]  \
  [get_cells {u_input_checker/cipher_reg[0]}]  \
  [get_cells {u_input_checker/cipher_reg[1]}]  \
  [get_cells {u_input_checker/cipher_reg[2]}]  \
  [get_cells {u_input_checker/cipher_reg[3]}]  \
  [get_cells u_input_checker/done_reg]  \
  [get_cells {u_input_checker/i_cur_reg[2]}]  \
  [get_cells {u_input_checker/i_cur_reg[3]}]  \
  [get_cells {u_input_checker/i_cur_reg[4]}]  \
  [get_cells {u_input_checker/i_cur_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[0]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[1]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[2]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[3]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[4]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[6]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[7]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[8]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[9]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[10]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[11]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[12]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[13]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[14]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[15]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[16]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[17]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[18]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[19]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[20]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[21]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[22]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[23]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[24]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[25]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[26]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[27]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[28]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[29]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[30]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[31]}] ]
group_path -weight 1.000000 -name R2O -from [list \
  [get_cells {u_input_taker/data_reg[0]}]  \
  [get_cells {u_input_taker/data_reg[1]}]  \
  [get_cells {u_input_taker/data_reg[2]}]  \
  [get_cells {u_input_taker/data_reg[3]}]  \
  [get_cells {u_input_taker/data_reg[4]}]  \
  [get_cells {u_input_taker/data_reg[5]}]  \
  [get_cells {u_input_taker/data_reg[6]}]  \
  [get_cells {u_input_taker/data_reg[7]}]  \
  [get_cells {u_input_taker/data_reg[8]}]  \
  [get_cells {u_input_taker/data_reg[9]}]  \
  [get_cells {u_input_taker/data_reg[10]}]  \
  [get_cells {u_input_taker/data_reg[11]}]  \
  [get_cells {u_input_taker/data_reg[12]}]  \
  [get_cells {u_input_taker/data_reg[13]}]  \
  [get_cells {u_input_taker/data_reg[14]}]  \
  [get_cells {u_input_taker/data_reg[15]}]  \
  [get_cells {u_input_taker/data_reg[16]}]  \
  [get_cells {u_input_taker/data_reg[17]}]  \
  [get_cells {u_input_taker/data_reg[18]}]  \
  [get_cells {u_input_taker/data_reg[19]}]  \
  [get_cells {u_input_taker/data_reg[20]}]  \
  [get_cells {u_input_taker/data_reg[21]}]  \
  [get_cells {u_input_taker/data_reg[22]}]  \
  [get_cells {u_input_taker/data_reg[23]}]  \
  [get_cells {u_input_taker/data_reg[24]}]  \
  [get_cells {u_input_taker/data_reg[25]}]  \
  [get_cells {u_input_taker/data_reg[26]}]  \
  [get_cells {u_input_taker/data_reg[27]}]  \
  [get_cells {u_input_taker/data_reg[28]}]  \
  [get_cells {u_input_taker/data_reg[29]}]  \
  [get_cells {u_input_taker/data_reg[30]}]  \
  [get_cells {u_input_taker/data_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[0]}]  \
  [get_cells {u_input_taker/key_out_reg[1]}]  \
  [get_cells {u_input_taker/key_out_reg[2]}]  \
  [get_cells {u_input_taker/key_out_reg[3]}]  \
  [get_cells {u_input_taker/key_out_reg[4]}]  \
  [get_cells {u_input_taker/key_out_reg[5]}]  \
  [get_cells {u_input_taker/key_out_reg[6]}]  \
  [get_cells {u_input_taker/key_out_reg[7]}]  \
  [get_cells {u_input_taker/key_out_reg[8]}]  \
  [get_cells {u_input_taker/key_out_reg[9]}]  \
  [get_cells {u_input_taker/key_out_reg[10]}]  \
  [get_cells {u_input_taker/key_out_reg[11]}]  \
  [get_cells {u_input_taker/key_out_reg[12]}]  \
  [get_cells {u_input_taker/key_out_reg[13]}]  \
  [get_cells {u_input_taker/key_out_reg[14]}]  \
  [get_cells {u_input_taker/key_out_reg[15]}]  \
  [get_cells {u_input_taker/key_out_reg[16]}]  \
  [get_cells {u_input_taker/key_out_reg[17]}]  \
  [get_cells {u_input_taker/key_out_reg[18]}]  \
  [get_cells {u_input_taker/key_out_reg[19]}]  \
  [get_cells {u_input_taker/key_out_reg[20]}]  \
  [get_cells {u_input_taker/key_out_reg[21]}]  \
  [get_cells {u_input_taker/key_out_reg[22]}]  \
  [get_cells {u_input_taker/key_out_reg[23]}]  \
  [get_cells {u_input_taker/key_out_reg[24]}]  \
  [get_cells {u_input_taker/key_out_reg[25]}]  \
  [get_cells {u_input_taker/key_out_reg[26]}]  \
  [get_cells {u_input_taker/key_out_reg[27]}]  \
  [get_cells {u_input_taker/key_out_reg[28]}]  \
  [get_cells {u_input_taker/key_out_reg[29]}]  \
  [get_cells {u_input_taker/key_out_reg[30]}]  \
  [get_cells {u_input_taker/key_out_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[32]}]  \
  [get_cells {u_input_taker/key_out_reg[33]}]  \
  [get_cells {u_input_taker/key_out_reg[34]}]  \
  [get_cells {u_input_taker/key_out_reg[35]}]  \
  [get_cells {u_input_taker/key_out_reg[36]}]  \
  [get_cells {u_input_taker/key_out_reg[37]}]  \
  [get_cells {u_input_taker/key_out_reg[38]}]  \
  [get_cells {u_input_taker/key_out_reg[39]}]  \
  [get_cells {u_input_taker/key_out_reg[40]}]  \
  [get_cells {u_input_taker/key_out_reg[41]}]  \
  [get_cells {u_input_taker/key_out_reg[42]}]  \
  [get_cells {u_input_taker/key_out_reg[43]}]  \
  [get_cells {u_input_taker/key_out_reg[44]}]  \
  [get_cells {u_input_taker/key_out_reg[45]}]  \
  [get_cells {u_input_taker/key_out_reg[46]}]  \
  [get_cells {u_input_taker/key_out_reg[47]}]  \
  [get_cells {u_input_taker/key_out_reg[48]}]  \
  [get_cells {u_input_taker/key_out_reg[49]}]  \
  [get_cells {u_input_taker/key_out_reg[50]}]  \
  [get_cells {u_input_taker/key_out_reg[51]}]  \
  [get_cells {u_input_taker/key_out_reg[52]}]  \
  [get_cells {u_input_taker/key_out_reg[53]}]  \
  [get_cells {u_input_taker/key_out_reg[54]}]  \
  [get_cells {u_input_taker/key_out_reg[55]}]  \
  [get_cells {u_input_taker/key_out_reg[56]}]  \
  [get_cells {u_input_taker/key_out_reg[57]}]  \
  [get_cells {u_input_taker/key_out_reg[58]}]  \
  [get_cells {u_input_taker/key_out_reg[59]}]  \
  [get_cells {u_input_taker/key_out_reg[60]}]  \
  [get_cells {u_input_taker/key_out_reg[61]}]  \
  [get_cells {u_input_taker/key_out_reg[62]}]  \
  [get_cells {u_input_taker/key_out_reg[63]}]  \
  [get_cells u_input_taker/done_reg]  \
  [get_cells {u_input_taker/state_reg[0]}]  \
  [get_cells {u_input_taker/state_reg[1]}]  \
  [get_cells {u_input_taker/state_reg[2]}]  \
  [get_cells {u_input_taker/state_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[0]}]  \
  [get_cells {u_input_taker/key_buf_reg[1]}]  \
  [get_cells {u_input_taker/key_buf_reg[2]}]  \
  [get_cells {u_input_taker/key_buf_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[4]}]  \
  [get_cells {u_input_taker/key_buf_reg[5]}]  \
  [get_cells {u_input_taker/key_buf_reg[6]}]  \
  [get_cells {u_input_taker/key_buf_reg[7]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[0]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[1]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[2]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[3]}]  \
  [get_cells u_input_taker/start_buf_reg]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[15]}]  \
  [get_cells u_simon/start_prev_reg]  \
  [get_cells u_simon/buffer_reg]  \
  [get_cells {u_simon/j_cur_reg[0]}]  \
  [get_cells {u_simon/j_cur_reg[1]}]  \
  [get_cells {u_simon/j_cur_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[0]}]  \
  [get_cells {u_output_giver/cipher_reg[1]}]  \
  [get_cells {u_output_giver/cipher_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[3]}]  \
  [get_cells u_output_giver/done_reg]  \
  [get_cells {u_output_giver/i_cur_reg[2]}]  \
  [get_cells {u_output_giver/i_cur_reg[3]}]  \
  [get_cells {u_output_giver/i_cur_reg[4]}]  \
  [get_cells {u_output_giver/i_cur_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[0]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[1]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[2]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[3]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[4]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[6]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[7]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[8]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[9]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[10]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[11]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[12]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[13]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[14]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[15]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[16]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[17]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[18]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[19]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[20]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[21]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[22]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[23]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[24]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[25]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[26]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[27]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[28]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[29]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[30]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[31]}]  \
  [get_cells {u_input_checker/cipher_reg[0]}]  \
  [get_cells {u_input_checker/cipher_reg[1]}]  \
  [get_cells {u_input_checker/cipher_reg[2]}]  \
  [get_cells {u_input_checker/cipher_reg[3]}]  \
  [get_cells u_input_checker/done_reg]  \
  [get_cells {u_input_checker/i_cur_reg[2]}]  \
  [get_cells {u_input_checker/i_cur_reg[3]}]  \
  [get_cells {u_input_checker/i_cur_reg[4]}]  \
  [get_cells {u_input_checker/i_cur_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[0]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[1]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[2]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[3]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[4]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[6]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[7]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[8]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[9]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[10]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[11]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[12]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[13]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[14]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[15]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[16]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[17]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[18]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[19]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[20]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[21]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[22]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[23]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[24]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[25]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[26]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[27]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[28]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[29]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[30]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[31]}] ] -to [list \
  [get_ports {cipher_pad[3]}]  \
  [get_ports {cipher_pad[2]}]  \
  [get_ports {cipher_pad[1]}]  \
  [get_ports {cipher_pad[0]}]  \
  [get_ports done_final_pad]  \
  [get_ports {out_txt_pad[3]}]  \
  [get_ports {out_txt_pad[2]}]  \
  [get_ports {out_txt_pad[1]}]  \
  [get_ports {out_txt_pad[0]}]  \
  [get_ports {test_pad[5]}]  \
  [get_ports {test_pad[4]}]  \
  [get_ports {test_pad[3]}]  \
  [get_ports {test_pad[2]}]  \
  [get_ports {test_pad[1]}]  \
  [get_ports {test_pad[0]}]  \
  [get_ports txt_done_final_pad] ]
group_path -weight 1.000000 -name R2R -from [list \
  [get_cells {u_input_taker/data_reg[0]}]  \
  [get_cells {u_input_taker/data_reg[1]}]  \
  [get_cells {u_input_taker/data_reg[2]}]  \
  [get_cells {u_input_taker/data_reg[3]}]  \
  [get_cells {u_input_taker/data_reg[4]}]  \
  [get_cells {u_input_taker/data_reg[5]}]  \
  [get_cells {u_input_taker/data_reg[6]}]  \
  [get_cells {u_input_taker/data_reg[7]}]  \
  [get_cells {u_input_taker/data_reg[8]}]  \
  [get_cells {u_input_taker/data_reg[9]}]  \
  [get_cells {u_input_taker/data_reg[10]}]  \
  [get_cells {u_input_taker/data_reg[11]}]  \
  [get_cells {u_input_taker/data_reg[12]}]  \
  [get_cells {u_input_taker/data_reg[13]}]  \
  [get_cells {u_input_taker/data_reg[14]}]  \
  [get_cells {u_input_taker/data_reg[15]}]  \
  [get_cells {u_input_taker/data_reg[16]}]  \
  [get_cells {u_input_taker/data_reg[17]}]  \
  [get_cells {u_input_taker/data_reg[18]}]  \
  [get_cells {u_input_taker/data_reg[19]}]  \
  [get_cells {u_input_taker/data_reg[20]}]  \
  [get_cells {u_input_taker/data_reg[21]}]  \
  [get_cells {u_input_taker/data_reg[22]}]  \
  [get_cells {u_input_taker/data_reg[23]}]  \
  [get_cells {u_input_taker/data_reg[24]}]  \
  [get_cells {u_input_taker/data_reg[25]}]  \
  [get_cells {u_input_taker/data_reg[26]}]  \
  [get_cells {u_input_taker/data_reg[27]}]  \
  [get_cells {u_input_taker/data_reg[28]}]  \
  [get_cells {u_input_taker/data_reg[29]}]  \
  [get_cells {u_input_taker/data_reg[30]}]  \
  [get_cells {u_input_taker/data_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[0]}]  \
  [get_cells {u_input_taker/key_out_reg[1]}]  \
  [get_cells {u_input_taker/key_out_reg[2]}]  \
  [get_cells {u_input_taker/key_out_reg[3]}]  \
  [get_cells {u_input_taker/key_out_reg[4]}]  \
  [get_cells {u_input_taker/key_out_reg[5]}]  \
  [get_cells {u_input_taker/key_out_reg[6]}]  \
  [get_cells {u_input_taker/key_out_reg[7]}]  \
  [get_cells {u_input_taker/key_out_reg[8]}]  \
  [get_cells {u_input_taker/key_out_reg[9]}]  \
  [get_cells {u_input_taker/key_out_reg[10]}]  \
  [get_cells {u_input_taker/key_out_reg[11]}]  \
  [get_cells {u_input_taker/key_out_reg[12]}]  \
  [get_cells {u_input_taker/key_out_reg[13]}]  \
  [get_cells {u_input_taker/key_out_reg[14]}]  \
  [get_cells {u_input_taker/key_out_reg[15]}]  \
  [get_cells {u_input_taker/key_out_reg[16]}]  \
  [get_cells {u_input_taker/key_out_reg[17]}]  \
  [get_cells {u_input_taker/key_out_reg[18]}]  \
  [get_cells {u_input_taker/key_out_reg[19]}]  \
  [get_cells {u_input_taker/key_out_reg[20]}]  \
  [get_cells {u_input_taker/key_out_reg[21]}]  \
  [get_cells {u_input_taker/key_out_reg[22]}]  \
  [get_cells {u_input_taker/key_out_reg[23]}]  \
  [get_cells {u_input_taker/key_out_reg[24]}]  \
  [get_cells {u_input_taker/key_out_reg[25]}]  \
  [get_cells {u_input_taker/key_out_reg[26]}]  \
  [get_cells {u_input_taker/key_out_reg[27]}]  \
  [get_cells {u_input_taker/key_out_reg[28]}]  \
  [get_cells {u_input_taker/key_out_reg[29]}]  \
  [get_cells {u_input_taker/key_out_reg[30]}]  \
  [get_cells {u_input_taker/key_out_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[32]}]  \
  [get_cells {u_input_taker/key_out_reg[33]}]  \
  [get_cells {u_input_taker/key_out_reg[34]}]  \
  [get_cells {u_input_taker/key_out_reg[35]}]  \
  [get_cells {u_input_taker/key_out_reg[36]}]  \
  [get_cells {u_input_taker/key_out_reg[37]}]  \
  [get_cells {u_input_taker/key_out_reg[38]}]  \
  [get_cells {u_input_taker/key_out_reg[39]}]  \
  [get_cells {u_input_taker/key_out_reg[40]}]  \
  [get_cells {u_input_taker/key_out_reg[41]}]  \
  [get_cells {u_input_taker/key_out_reg[42]}]  \
  [get_cells {u_input_taker/key_out_reg[43]}]  \
  [get_cells {u_input_taker/key_out_reg[44]}]  \
  [get_cells {u_input_taker/key_out_reg[45]}]  \
  [get_cells {u_input_taker/key_out_reg[46]}]  \
  [get_cells {u_input_taker/key_out_reg[47]}]  \
  [get_cells {u_input_taker/key_out_reg[48]}]  \
  [get_cells {u_input_taker/key_out_reg[49]}]  \
  [get_cells {u_input_taker/key_out_reg[50]}]  \
  [get_cells {u_input_taker/key_out_reg[51]}]  \
  [get_cells {u_input_taker/key_out_reg[52]}]  \
  [get_cells {u_input_taker/key_out_reg[53]}]  \
  [get_cells {u_input_taker/key_out_reg[54]}]  \
  [get_cells {u_input_taker/key_out_reg[55]}]  \
  [get_cells {u_input_taker/key_out_reg[56]}]  \
  [get_cells {u_input_taker/key_out_reg[57]}]  \
  [get_cells {u_input_taker/key_out_reg[58]}]  \
  [get_cells {u_input_taker/key_out_reg[59]}]  \
  [get_cells {u_input_taker/key_out_reg[60]}]  \
  [get_cells {u_input_taker/key_out_reg[61]}]  \
  [get_cells {u_input_taker/key_out_reg[62]}]  \
  [get_cells {u_input_taker/key_out_reg[63]}]  \
  [get_cells u_input_taker/done_reg]  \
  [get_cells {u_input_taker/state_reg[0]}]  \
  [get_cells {u_input_taker/state_reg[1]}]  \
  [get_cells {u_input_taker/state_reg[2]}]  \
  [get_cells {u_input_taker/state_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[0]}]  \
  [get_cells {u_input_taker/key_buf_reg[1]}]  \
  [get_cells {u_input_taker/key_buf_reg[2]}]  \
  [get_cells {u_input_taker/key_buf_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[4]}]  \
  [get_cells {u_input_taker/key_buf_reg[5]}]  \
  [get_cells {u_input_taker/key_buf_reg[6]}]  \
  [get_cells {u_input_taker/key_buf_reg[7]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[0]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[1]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[2]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[3]}]  \
  [get_cells u_input_taker/start_buf_reg]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[15]}]  \
  [get_cells u_simon/start_prev_reg]  \
  [get_cells u_simon/buffer_reg]  \
  [get_cells {u_simon/j_cur_reg[0]}]  \
  [get_cells {u_simon/j_cur_reg[1]}]  \
  [get_cells {u_simon/j_cur_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[0]}]  \
  [get_cells {u_output_giver/cipher_reg[1]}]  \
  [get_cells {u_output_giver/cipher_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[3]}]  \
  [get_cells u_output_giver/done_reg]  \
  [get_cells {u_output_giver/i_cur_reg[2]}]  \
  [get_cells {u_output_giver/i_cur_reg[3]}]  \
  [get_cells {u_output_giver/i_cur_reg[4]}]  \
  [get_cells {u_output_giver/i_cur_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[0]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[1]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[2]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[3]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[4]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[6]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[7]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[8]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[9]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[10]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[11]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[12]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[13]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[14]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[15]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[16]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[17]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[18]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[19]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[20]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[21]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[22]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[23]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[24]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[25]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[26]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[27]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[28]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[29]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[30]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[31]}]  \
  [get_cells {u_input_checker/cipher_reg[0]}]  \
  [get_cells {u_input_checker/cipher_reg[1]}]  \
  [get_cells {u_input_checker/cipher_reg[2]}]  \
  [get_cells {u_input_checker/cipher_reg[3]}]  \
  [get_cells u_input_checker/done_reg]  \
  [get_cells {u_input_checker/i_cur_reg[2]}]  \
  [get_cells {u_input_checker/i_cur_reg[3]}]  \
  [get_cells {u_input_checker/i_cur_reg[4]}]  \
  [get_cells {u_input_checker/i_cur_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[0]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[1]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[2]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[3]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[4]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[6]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[7]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[8]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[9]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[10]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[11]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[12]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[13]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[14]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[15]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[16]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[17]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[18]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[19]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[20]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[21]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[22]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[23]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[24]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[25]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[26]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[27]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[28]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[29]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[30]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[31]}] ] -to [list \
  [get_cells {u_input_taker/data_reg[0]}]  \
  [get_cells {u_input_taker/data_reg[1]}]  \
  [get_cells {u_input_taker/data_reg[2]}]  \
  [get_cells {u_input_taker/data_reg[3]}]  \
  [get_cells {u_input_taker/data_reg[4]}]  \
  [get_cells {u_input_taker/data_reg[5]}]  \
  [get_cells {u_input_taker/data_reg[6]}]  \
  [get_cells {u_input_taker/data_reg[7]}]  \
  [get_cells {u_input_taker/data_reg[8]}]  \
  [get_cells {u_input_taker/data_reg[9]}]  \
  [get_cells {u_input_taker/data_reg[10]}]  \
  [get_cells {u_input_taker/data_reg[11]}]  \
  [get_cells {u_input_taker/data_reg[12]}]  \
  [get_cells {u_input_taker/data_reg[13]}]  \
  [get_cells {u_input_taker/data_reg[14]}]  \
  [get_cells {u_input_taker/data_reg[15]}]  \
  [get_cells {u_input_taker/data_reg[16]}]  \
  [get_cells {u_input_taker/data_reg[17]}]  \
  [get_cells {u_input_taker/data_reg[18]}]  \
  [get_cells {u_input_taker/data_reg[19]}]  \
  [get_cells {u_input_taker/data_reg[20]}]  \
  [get_cells {u_input_taker/data_reg[21]}]  \
  [get_cells {u_input_taker/data_reg[22]}]  \
  [get_cells {u_input_taker/data_reg[23]}]  \
  [get_cells {u_input_taker/data_reg[24]}]  \
  [get_cells {u_input_taker/data_reg[25]}]  \
  [get_cells {u_input_taker/data_reg[26]}]  \
  [get_cells {u_input_taker/data_reg[27]}]  \
  [get_cells {u_input_taker/data_reg[28]}]  \
  [get_cells {u_input_taker/data_reg[29]}]  \
  [get_cells {u_input_taker/data_reg[30]}]  \
  [get_cells {u_input_taker/data_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[0]}]  \
  [get_cells {u_input_taker/key_out_reg[1]}]  \
  [get_cells {u_input_taker/key_out_reg[2]}]  \
  [get_cells {u_input_taker/key_out_reg[3]}]  \
  [get_cells {u_input_taker/key_out_reg[4]}]  \
  [get_cells {u_input_taker/key_out_reg[5]}]  \
  [get_cells {u_input_taker/key_out_reg[6]}]  \
  [get_cells {u_input_taker/key_out_reg[7]}]  \
  [get_cells {u_input_taker/key_out_reg[8]}]  \
  [get_cells {u_input_taker/key_out_reg[9]}]  \
  [get_cells {u_input_taker/key_out_reg[10]}]  \
  [get_cells {u_input_taker/key_out_reg[11]}]  \
  [get_cells {u_input_taker/key_out_reg[12]}]  \
  [get_cells {u_input_taker/key_out_reg[13]}]  \
  [get_cells {u_input_taker/key_out_reg[14]}]  \
  [get_cells {u_input_taker/key_out_reg[15]}]  \
  [get_cells {u_input_taker/key_out_reg[16]}]  \
  [get_cells {u_input_taker/key_out_reg[17]}]  \
  [get_cells {u_input_taker/key_out_reg[18]}]  \
  [get_cells {u_input_taker/key_out_reg[19]}]  \
  [get_cells {u_input_taker/key_out_reg[20]}]  \
  [get_cells {u_input_taker/key_out_reg[21]}]  \
  [get_cells {u_input_taker/key_out_reg[22]}]  \
  [get_cells {u_input_taker/key_out_reg[23]}]  \
  [get_cells {u_input_taker/key_out_reg[24]}]  \
  [get_cells {u_input_taker/key_out_reg[25]}]  \
  [get_cells {u_input_taker/key_out_reg[26]}]  \
  [get_cells {u_input_taker/key_out_reg[27]}]  \
  [get_cells {u_input_taker/key_out_reg[28]}]  \
  [get_cells {u_input_taker/key_out_reg[29]}]  \
  [get_cells {u_input_taker/key_out_reg[30]}]  \
  [get_cells {u_input_taker/key_out_reg[31]}]  \
  [get_cells {u_input_taker/key_out_reg[32]}]  \
  [get_cells {u_input_taker/key_out_reg[33]}]  \
  [get_cells {u_input_taker/key_out_reg[34]}]  \
  [get_cells {u_input_taker/key_out_reg[35]}]  \
  [get_cells {u_input_taker/key_out_reg[36]}]  \
  [get_cells {u_input_taker/key_out_reg[37]}]  \
  [get_cells {u_input_taker/key_out_reg[38]}]  \
  [get_cells {u_input_taker/key_out_reg[39]}]  \
  [get_cells {u_input_taker/key_out_reg[40]}]  \
  [get_cells {u_input_taker/key_out_reg[41]}]  \
  [get_cells {u_input_taker/key_out_reg[42]}]  \
  [get_cells {u_input_taker/key_out_reg[43]}]  \
  [get_cells {u_input_taker/key_out_reg[44]}]  \
  [get_cells {u_input_taker/key_out_reg[45]}]  \
  [get_cells {u_input_taker/key_out_reg[46]}]  \
  [get_cells {u_input_taker/key_out_reg[47]}]  \
  [get_cells {u_input_taker/key_out_reg[48]}]  \
  [get_cells {u_input_taker/key_out_reg[49]}]  \
  [get_cells {u_input_taker/key_out_reg[50]}]  \
  [get_cells {u_input_taker/key_out_reg[51]}]  \
  [get_cells {u_input_taker/key_out_reg[52]}]  \
  [get_cells {u_input_taker/key_out_reg[53]}]  \
  [get_cells {u_input_taker/key_out_reg[54]}]  \
  [get_cells {u_input_taker/key_out_reg[55]}]  \
  [get_cells {u_input_taker/key_out_reg[56]}]  \
  [get_cells {u_input_taker/key_out_reg[57]}]  \
  [get_cells {u_input_taker/key_out_reg[58]}]  \
  [get_cells {u_input_taker/key_out_reg[59]}]  \
  [get_cells {u_input_taker/key_out_reg[60]}]  \
  [get_cells {u_input_taker/key_out_reg[61]}]  \
  [get_cells {u_input_taker/key_out_reg[62]}]  \
  [get_cells {u_input_taker/key_out_reg[63]}]  \
  [get_cells u_input_taker/done_reg]  \
  [get_cells {u_input_taker/state_reg[0]}]  \
  [get_cells {u_input_taker/state_reg[1]}]  \
  [get_cells {u_input_taker/state_reg[2]}]  \
  [get_cells {u_input_taker/state_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[0]}]  \
  [get_cells {u_input_taker/key_buf_reg[1]}]  \
  [get_cells {u_input_taker/key_buf_reg[2]}]  \
  [get_cells {u_input_taker/key_buf_reg[3]}]  \
  [get_cells {u_input_taker/key_buf_reg[4]}]  \
  [get_cells {u_input_taker/key_buf_reg[5]}]  \
  [get_cells {u_input_taker/key_buf_reg[6]}]  \
  [get_cells {u_input_taker/key_buf_reg[7]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[0]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[1]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[2]}]  \
  [get_cells {u_input_taker/Plaintxt_buf_reg[3]}]  \
  [get_cells u_input_taker/start_buf_reg]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key0_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key1_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key2_reg[15]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[0]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[1]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[2]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[3]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[4]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[5]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[6]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[7]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[8]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[9]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[10]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[11]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[12]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[13]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[14]}]  \
  [get_cells {u_simon/u_key_gen/key3_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/i_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/x_cur_reg[15]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[0]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[1]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[2]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[3]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[4]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[5]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[6]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[7]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[8]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[9]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[10]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[11]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[12]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[13]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[14]}]  \
  [get_cells {u_simon/u_encrypt/y_cur_reg[15]}]  \
  [get_cells u_simon/start_prev_reg]  \
  [get_cells u_simon/buffer_reg]  \
  [get_cells {u_simon/j_cur_reg[0]}]  \
  [get_cells {u_simon/j_cur_reg[1]}]  \
  [get_cells {u_simon/j_cur_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[0]}]  \
  [get_cells {u_output_giver/cipher_reg[1]}]  \
  [get_cells {u_output_giver/cipher_reg[2]}]  \
  [get_cells {u_output_giver/cipher_reg[3]}]  \
  [get_cells u_output_giver/done_reg]  \
  [get_cells {u_output_giver/i_cur_reg[2]}]  \
  [get_cells {u_output_giver/i_cur_reg[3]}]  \
  [get_cells {u_output_giver/i_cur_reg[4]}]  \
  [get_cells {u_output_giver/i_cur_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[0]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[1]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[2]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[3]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[4]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[5]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[6]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[7]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[8]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[9]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[10]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[11]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[12]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[13]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[14]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[15]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[16]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[17]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[18]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[19]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[20]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[21]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[22]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[23]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[24]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[25]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[26]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[27]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[28]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[29]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[30]}]  \
  [get_cells {u_output_giver/buffer_reg_reg[31]}]  \
  [get_cells {u_input_checker/cipher_reg[0]}]  \
  [get_cells {u_input_checker/cipher_reg[1]}]  \
  [get_cells {u_input_checker/cipher_reg[2]}]  \
  [get_cells {u_input_checker/cipher_reg[3]}]  \
  [get_cells u_input_checker/done_reg]  \
  [get_cells {u_input_checker/i_cur_reg[2]}]  \
  [get_cells {u_input_checker/i_cur_reg[3]}]  \
  [get_cells {u_input_checker/i_cur_reg[4]}]  \
  [get_cells {u_input_checker/i_cur_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[0]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[1]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[2]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[3]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[4]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[5]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[6]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[7]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[8]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[9]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[10]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[11]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[12]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[13]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[14]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[15]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[16]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[17]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[18]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[19]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[20]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[21]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[22]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[23]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[24]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[25]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[26]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[27]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[28]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[29]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[30]}]  \
  [get_cells {u_input_checker/buffer_reg_reg[31]}] ]
group_path -weight 1.000000 -name I2O -from [list \
  [get_ports clk_pad]  \
  [get_ports reset_pad]  \
  [get_ports {key_pad[7]}]  \
  [get_ports {key_pad[6]}]  \
  [get_ports {key_pad[5]}]  \
  [get_ports {key_pad[4]}]  \
  [get_ports {key_pad[3]}]  \
  [get_ports {key_pad[2]}]  \
  [get_ports {key_pad[1]}]  \
  [get_ports {key_pad[0]}]  \
  [get_ports {Plaintxt_pad[3]}]  \
  [get_ports {Plaintxt_pad[2]}]  \
  [get_ports {Plaintxt_pad[1]}]  \
  [get_ports {Plaintxt_pad[0]}]  \
  [get_ports start_pad] ] -to [list \
  [get_ports {cipher_pad[3]}]  \
  [get_ports {cipher_pad[2]}]  \
  [get_ports {cipher_pad[1]}]  \
  [get_ports {cipher_pad[0]}]  \
  [get_ports done_final_pad]  \
  [get_ports {out_txt_pad[3]}]  \
  [get_ports {out_txt_pad[2]}]  \
  [get_ports {out_txt_pad[1]}]  \
  [get_ports {out_txt_pad[0]}]  \
  [get_ports {test_pad[5]}]  \
  [get_ports {test_pad[4]}]  \
  [get_ports {test_pad[3]}]  \
  [get_ports {test_pad[2]}]  \
  [get_ports {test_pad[1]}]  \
  [get_ports {test_pad[0]}]  \
  [get_ports txt_done_final_pad] ]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports reset_pad]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {key_pad[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {key_pad[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {key_pad[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {key_pad[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {key_pad[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {key_pad[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {key_pad[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {key_pad[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {Plaintxt_pad[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {Plaintxt_pad[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {Plaintxt_pad[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {Plaintxt_pad[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports start_pad]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports reset_pad]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {key_pad[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {key_pad[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {key_pad[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {key_pad[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {key_pad[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {key_pad[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {key_pad[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {key_pad[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {Plaintxt_pad[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {Plaintxt_pad[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {Plaintxt_pad[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {Plaintxt_pad[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports start_pad]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {cipher_pad[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {cipher_pad[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {cipher_pad[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {cipher_pad[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports done_final_pad]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {out_txt_pad[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {out_txt_pad[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {out_txt_pad[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {out_txt_pad[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {test_pad[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {test_pad[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {test_pad[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {test_pad[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {test_pad[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {test_pad[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports txt_done_final_pad]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {cipher_pad[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {cipher_pad[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {cipher_pad[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {cipher_pad[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports done_final_pad]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {out_txt_pad[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {out_txt_pad[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {out_txt_pad[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {out_txt_pad[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {test_pad[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {test_pad[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {test_pad[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {test_pad[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {test_pad[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports {test_pad[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.3 [get_ports txt_done_final_pad]
set_input_transition -min 0.1 [get_ports reset_pad]
set_input_transition -max 0.2 [get_ports reset_pad]
set_input_transition -min 0.1 [get_ports {key_pad[7]}]
set_input_transition -max 0.2 [get_ports {key_pad[7]}]
set_input_transition -min 0.1 [get_ports {key_pad[6]}]
set_input_transition -max 0.2 [get_ports {key_pad[6]}]
set_input_transition -min 0.1 [get_ports {key_pad[5]}]
set_input_transition -max 0.2 [get_ports {key_pad[5]}]
set_input_transition -min 0.1 [get_ports {key_pad[4]}]
set_input_transition -max 0.2 [get_ports {key_pad[4]}]
set_input_transition -min 0.1 [get_ports {key_pad[3]}]
set_input_transition -max 0.2 [get_ports {key_pad[3]}]
set_input_transition -min 0.1 [get_ports {key_pad[2]}]
set_input_transition -max 0.2 [get_ports {key_pad[2]}]
set_input_transition -min 0.1 [get_ports {key_pad[1]}]
set_input_transition -max 0.2 [get_ports {key_pad[1]}]
set_input_transition -min 0.1 [get_ports {key_pad[0]}]
set_input_transition -max 0.2 [get_ports {key_pad[0]}]
set_input_transition -min 0.1 [get_ports {Plaintxt_pad[3]}]
set_input_transition -max 0.2 [get_ports {Plaintxt_pad[3]}]
set_input_transition -min 0.1 [get_ports {Plaintxt_pad[2]}]
set_input_transition -max 0.2 [get_ports {Plaintxt_pad[2]}]
set_input_transition -min 0.1 [get_ports {Plaintxt_pad[1]}]
set_input_transition -max 0.2 [get_ports {Plaintxt_pad[1]}]
set_input_transition -min 0.1 [get_ports {Plaintxt_pad[0]}]
set_input_transition -max 0.2 [get_ports {Plaintxt_pad[0]}]
set_input_transition -min 0.1 [get_ports start_pad]
set_input_transition -max 0.2 [get_ports start_pad]
set_wire_load_mode "enclosed"
set_dont_use true [get_lib_cells tsl18fs120_scl_ss/slbhb2]
set_dont_use true [get_lib_cells tsl18fs120_scl_ss/slbhb1]
set_dont_use true [get_lib_cells tsl18fs120_scl_ss/slbhb4]
set_clock_latency -source -max 0.2 [get_clocks clk]
set_clock_latency -source -min 0.15 [get_clocks clk]
set_clock_uncertainty -setup 0.01 [get_clocks clk]
set_clock_uncertainty -hold 0.01 [get_clocks clk]
