
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jul 17 2025 16:47:26 IST (Jul 17 2025 11:17:26 UTC)

// Verification Directory fv/Top 

module input_taker_5(clk, reset, key, Plaintxt, start, data, key_out,
     done);
  input clk, reset, start;
  input [7:0] key;
  input [3:0] Plaintxt;
  output [31:0] data;
  output [63:0] key_out;
  output done;
  wire clk, reset, start;
  wire [7:0] key;
  wire [3:0] Plaintxt;
  wire [31:0] data;
  wire [63:0] key_out;
  wire done;
  wire [3:0] state;
  wire [7:0] key_buf;
  wire [3:0] Plaintxt_buf;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, start_buf;
  inv0d0 g2478(.I (start), .ZN (n_226));
  dfnrq1 done_reg(.CP (clk), .D (n_225), .Q (done));
  nr13d1 g2507__2398(.A1 (state[0]), .A2 (reset), .A3 (n_227), .ZN
       (n_225));
  dfnrq1 start_buf_reg(.CP (clk), .D (n_223), .Q (start_buf));
  nd02d1 g2509__5107(.A1 (n_224), .A2 (state[3]), .ZN (n_227));
  dfnrq1 \key_buf_reg[0] (.CP (clk), .D (key[0]), .Q (key_buf[0]));
  dfnrq1 \key_buf_reg[5] (.CP (clk), .D (key[5]), .Q (key_buf[5]));
  dfnrq1 \key_buf_reg[6] (.CP (clk), .D (key[6]), .Q (key_buf[6]));
  dfnrq1 \Plaintxt_buf_reg[2] (.CP (clk), .D (Plaintxt[2]), .Q
       (Plaintxt_buf[2]));
  dfnrq1 \Plaintxt_buf_reg[0] (.CP (clk), .D (Plaintxt[0]), .Q
       (Plaintxt_buf[0]));
  dfnrq1 \Plaintxt_buf_reg[3] (.CP (clk), .D (Plaintxt[3]), .Q
       (Plaintxt_buf[3]));
  dfnrq1 \key_buf_reg[7] (.CP (clk), .D (key[7]), .Q (key_buf[7]));
  nr02d1 g2517__6260(.A1 (state[2]), .A2 (state[1]), .ZN (n_224));
  dfnrq1 \key_buf_reg[1] (.CP (clk), .D (key[1]), .Q (key_buf[1]));
  dfnrq1 \key_buf_reg[2] (.CP (clk), .D (key[2]), .Q (key_buf[2]));
  dfnrq1 \key_buf_reg[3] (.CP (clk), .D (key[3]), .Q (key_buf[3]));
  dfnrq1 \key_buf_reg[4] (.CP (clk), .D (key[4]), .Q (key_buf[4]));
  nr02d0 g2522__4319(.A1 (reset), .A2 (n_226), .ZN (n_223));
  dfnrq1 \Plaintxt_buf_reg[1] (.CP (clk), .D (Plaintxt[1]), .Q
       (Plaintxt_buf[1]));
  dfnrq1 \data_reg[0] (.CP (clk), .D (n_41), .Q (data[0]));
  dfnrq1 \data_reg[1] (.CP (clk), .D (n_38), .Q (data[1]));
  dfnrq1 \data_reg[2] (.CP (clk), .D (n_43), .Q (data[2]));
  dfnrq1 \data_reg[3] (.CP (clk), .D (n_39), .Q (data[3]));
  dfnrq1 \data_reg[4] (.CP (clk), .D (n_154), .Q (data[4]));
  dfnrq1 \data_reg[5] (.CP (clk), .D (n_146), .Q (data[5]));
  dfnrq1 \data_reg[6] (.CP (clk), .D (n_145), .Q (data[6]));
  dfnrq1 \data_reg[7] (.CP (clk), .D (n_144), .Q (data[7]));
  dfnrq1 \data_reg[8] (.CP (clk), .D (n_206), .Q (data[8]));
  dfnrq1 \data_reg[9] (.CP (clk), .D (n_205), .Q (data[9]));
  dfnrq1 \data_reg[10] (.CP (clk), .D (n_204), .Q (data[10]));
  dfnrq1 \data_reg[11] (.CP (clk), .D (n_203), .Q (data[11]));
  dfnrq1 \data_reg[12] (.CP (clk), .D (n_182), .Q (data[12]));
  dfnrq1 \data_reg[13] (.CP (clk), .D (n_181), .Q (data[13]));
  dfnrq1 \data_reg[14] (.CP (clk), .D (n_180), .Q (data[14]));
  dfnrq1 \data_reg[15] (.CP (clk), .D (n_179), .Q (data[15]));
  dfnrq1 \data_reg[16] (.CP (clk), .D (n_178), .Q (data[16]));
  dfnrq1 \data_reg[17] (.CP (clk), .D (n_175), .Q (data[17]));
  dfnrq1 \data_reg[18] (.CP (clk), .D (n_171), .Q (data[18]));
  dfnrq1 \data_reg[19] (.CP (clk), .D (n_170), .Q (data[19]));
  dfnrq1 \data_reg[20] (.CP (clk), .D (n_189), .Q (data[20]));
  dfnrq1 \data_reg[21] (.CP (clk), .D (n_190), .Q (data[21]));
  dfnrq1 \data_reg[22] (.CP (clk), .D (n_188), .Q (data[22]));
  dfnrq1 \data_reg[23] (.CP (clk), .D (n_187), .Q (data[23]));
  dfnrq1 \data_reg[24] (.CP (clk), .D (n_208), .Q (data[24]));
  dfnrq1 \data_reg[25] (.CP (clk), .D (n_207), .Q (data[25]));
  dfnrq1 \data_reg[26] (.CP (clk), .D (n_216), .Q (data[26]));
  dfnrq1 \data_reg[27] (.CP (clk), .D (n_218), .Q (data[27]));
  dfnrq1 \data_reg[28] (.CP (clk), .D (n_159), .Q (data[28]));
  dfnrq1 \data_reg[29] (.CP (clk), .D (n_158), .Q (data[29]));
  dfnrq1 \data_reg[30] (.CP (clk), .D (n_157), .Q (data[30]));
  dfnrq1 \data_reg[31] (.CP (clk), .D (n_177), .Q (data[31]));
  dfnrq1 \key_out_reg[0] (.CP (clk), .D (n_47), .Q (key_out[0]));
  dfnrq1 \key_out_reg[1] (.CP (clk), .D (n_36), .Q (key_out[1]));
  dfnrq1 \key_out_reg[2] (.CP (clk), .D (n_46), .Q (key_out[2]));
  dfnrq1 \key_out_reg[3] (.CP (clk), .D (n_40), .Q (key_out[3]));
  dfnrq1 \key_out_reg[4] (.CP (clk), .D (n_48), .Q (key_out[4]));
  dfnrq1 \key_out_reg[5] (.CP (clk), .D (n_45), .Q (key_out[5]));
  dfnrq1 \key_out_reg[6] (.CP (clk), .D (n_44), .Q (key_out[6]));
  dfnrq1 \key_out_reg[7] (.CP (clk), .D (n_49), .Q (key_out[7]));
  dfnrq1 \key_out_reg[8] (.CP (clk), .D (n_143), .Q (key_out[8]));
  dfnrq1 \key_out_reg[9] (.CP (clk), .D (n_142), .Q (key_out[9]));
  dfnrq1 \key_out_reg[10] (.CP (clk), .D (n_141), .Q (key_out[10]));
  dfnrq1 \key_out_reg[11] (.CP (clk), .D (n_140), .Q (key_out[11]));
  dfnrq1 \key_out_reg[12] (.CP (clk), .D (n_139), .Q (key_out[12]));
  dfnrq1 \key_out_reg[13] (.CP (clk), .D (n_138), .Q (key_out[13]));
  dfnrq1 \key_out_reg[14] (.CP (clk), .D (n_137), .Q (key_out[14]));
  dfnrq1 \key_out_reg[15] (.CP (clk), .D (n_136), .Q (key_out[15]));
  dfnrq1 \key_out_reg[16] (.CP (clk), .D (n_202), .Q (key_out[16]));
  dfnrq1 \key_out_reg[17] (.CP (clk), .D (n_201), .Q (key_out[17]));
  dfnrq1 \key_out_reg[18] (.CP (clk), .D (n_200), .Q (key_out[18]));
  dfnrq1 \key_out_reg[19] (.CP (clk), .D (n_199), .Q (key_out[19]));
  dfnrq1 \key_out_reg[20] (.CP (clk), .D (n_219), .Q (key_out[20]));
  dfnrq1 \key_out_reg[21] (.CP (clk), .D (n_197), .Q (key_out[21]));
  dfnrq1 \key_out_reg[22] (.CP (clk), .D (n_196), .Q (key_out[22]));
  dfnrq1 \key_out_reg[23] (.CP (clk), .D (n_195), .Q (key_out[23]));
  dfnrq1 \key_out_reg[24] (.CP (clk), .D (n_198), .Q (key_out[24]));
  dfnrq1 \key_out_reg[25] (.CP (clk), .D (n_156), .Q (key_out[25]));
  dfnrq1 \key_out_reg[26] (.CP (clk), .D (n_176), .Q (key_out[26]));
  dfnrq1 \key_out_reg[27] (.CP (clk), .D (n_174), .Q (key_out[27]));
  dfnrq1 \key_out_reg[28] (.CP (clk), .D (n_173), .Q (key_out[28]));
  dfnrq1 \key_out_reg[29] (.CP (clk), .D (n_172), .Q (key_out[29]));
  dfnrq1 \key_out_reg[30] (.CP (clk), .D (n_169), .Q (key_out[30]));
  dfnrq1 \key_out_reg[31] (.CP (clk), .D (n_168), .Q (key_out[31]));
  dfnrq1 \key_out_reg[32] (.CP (clk), .D (n_167), .Q (key_out[32]));
  dfnrq1 \key_out_reg[33] (.CP (clk), .D (n_166), .Q (key_out[33]));
  dfnrq1 \key_out_reg[34] (.CP (clk), .D (n_165), .Q (key_out[34]));
  dfnrq1 \key_out_reg[35] (.CP (clk), .D (n_164), .Q (key_out[35]));
  dfnrq1 \key_out_reg[36] (.CP (clk), .D (n_163), .Q (key_out[36]));
  dfnrq1 \key_out_reg[37] (.CP (clk), .D (n_162), .Q (key_out[37]));
  dfnrq1 \key_out_reg[38] (.CP (clk), .D (n_161), .Q (key_out[38]));
  dfnrq1 \key_out_reg[39] (.CP (clk), .D (n_160), .Q (key_out[39]));
  dfnrq1 \key_out_reg[40] (.CP (clk), .D (n_186), .Q (key_out[40]));
  dfnrq1 \key_out_reg[41] (.CP (clk), .D (n_185), .Q (key_out[41]));
  dfnrq1 \key_out_reg[42] (.CP (clk), .D (n_184), .Q (key_out[42]));
  dfnrq1 \key_out_reg[43] (.CP (clk), .D (n_183), .Q (key_out[43]));
  dfnrq1 \key_out_reg[44] (.CP (clk), .D (n_194), .Q (key_out[44]));
  dfnrq1 \key_out_reg[45] (.CP (clk), .D (n_193), .Q (key_out[45]));
  dfnrq1 \key_out_reg[46] (.CP (clk), .D (n_192), .Q (key_out[46]));
  dfnrq1 \key_out_reg[47] (.CP (clk), .D (n_191), .Q (key_out[47]));
  dfnrq1 \key_out_reg[48] (.CP (clk), .D (n_217), .Q (key_out[48]));
  dfnrq1 \key_out_reg[49] (.CP (clk), .D (n_215), .Q (key_out[49]));
  dfnrq1 \key_out_reg[50] (.CP (clk), .D (n_214), .Q (key_out[50]));
  dfnrq1 \key_out_reg[51] (.CP (clk), .D (n_213), .Q (key_out[51]));
  dfnrq1 \key_out_reg[52] (.CP (clk), .D (n_212), .Q (key_out[52]));
  dfnrq1 \key_out_reg[53] (.CP (clk), .D (n_211), .Q (key_out[53]));
  dfnrq1 \key_out_reg[54] (.CP (clk), .D (n_210), .Q (key_out[54]));
  dfnrq1 \key_out_reg[55] (.CP (clk), .D (n_209), .Q (key_out[55]));
  dfnrq1 \key_out_reg[56] (.CP (clk), .D (n_155), .Q (key_out[56]));
  dfnrq1 \key_out_reg[57] (.CP (clk), .D (n_153), .Q (key_out[57]));
  dfnrq1 \key_out_reg[58] (.CP (clk), .D (n_152), .Q (key_out[58]));
  dfnrq1 \key_out_reg[59] (.CP (clk), .D (n_151), .Q (key_out[59]));
  dfnrq1 \key_out_reg[60] (.CP (clk), .D (n_150), .Q (key_out[60]));
  dfnrq1 \key_out_reg[61] (.CP (clk), .D (n_149), .Q (key_out[61]));
  dfnrq1 \key_out_reg[62] (.CP (clk), .D (n_148), .Q (key_out[62]));
  dfnrq1 \key_out_reg[63] (.CP (clk), .D (n_147), .Q (key_out[63]));
  dfnrq1 \state_reg[2] (.CP (clk), .D (n_221), .Q (state[2]));
  dfnrq1 \state_reg[3] (.CP (clk), .D (n_116), .Q (state[3]));
  aoi31d1 g4445__8428(.A (reset), .B1 (n_135), .B2 (n_22), .B3 (n_2),
       .ZN (n_222));
  aoi31d1 g4491__5526(.A (reset), .B1 (n_29), .B2 (n_27), .B3 (n_37),
       .ZN (n_221));
  aoi31d1 g4492__6783(.A (reset), .B1 (n_22), .B2 (n_27), .B3 (n_42),
       .ZN (n_220));
  nr02d1 g4534__3680(.A1 (reset), .A2 (n_89), .ZN (n_219));
  nr02d1 g4535__1617(.A1 (reset), .A2 (n_71), .ZN (n_218));
  nr02d1 g4536__2802(.A1 (reset), .A2 (n_70), .ZN (n_217));
  nr02d1 g4537__1705(.A1 (reset), .A2 (n_73), .ZN (n_216));
  nr02d1 g4538__5122(.A1 (reset), .A2 (n_69), .ZN (n_215));
  nr02d1 g4539__8246(.A1 (reset), .A2 (n_63), .ZN (n_214));
  nr02d1 g4540__7098(.A1 (reset), .A2 (n_68), .ZN (n_213));
  nr02d1 g4541__6131(.A1 (reset), .A2 (n_67), .ZN (n_212));
  nr02d1 g4542__1881(.A1 (reset), .A2 (n_66), .ZN (n_211));
  nr02d1 g4543__5115(.A1 (reset), .A2 (n_65), .ZN (n_210));
  nr02d1 g4544__7482(.A1 (reset), .A2 (n_64), .ZN (n_209));
  nr02d1 g4545__4733(.A1 (reset), .A2 (n_98), .ZN (n_208));
  nr02d1 g4546__6161(.A1 (reset), .A2 (n_72), .ZN (n_207));
  nr02d1 g4547__9315(.A1 (reset), .A2 (n_97), .ZN (n_206));
  nr02d1 g4548__9945(.A1 (reset), .A2 (n_96), .ZN (n_205));
  nr02d1 g4549__2883(.A1 (reset), .A2 (n_95), .ZN (n_204));
  nr02d1 g4550__2346(.A1 (reset), .A2 (n_94), .ZN (n_203));
  nr02d1 g4551__1666(.A1 (reset), .A2 (n_93), .ZN (n_202));
  nr02d1 g4552__7410(.A1 (reset), .A2 (n_92), .ZN (n_201));
  nr02d1 g4553__6417(.A1 (reset), .A2 (n_91), .ZN (n_200));
  nr02d1 g4554__5477(.A1 (reset), .A2 (n_90), .ZN (n_199));
  nr02d1 g4555__2398(.A1 (reset), .A2 (n_58), .ZN (n_198));
  nr02d1 g4556__5107(.A1 (reset), .A2 (n_88), .ZN (n_197));
  nr02d1 g4557__6260(.A1 (reset), .A2 (n_87), .ZN (n_196));
  nr02d1 g4558__4319(.A1 (reset), .A2 (n_86), .ZN (n_195));
  nr02d1 g4559__8428(.A1 (reset), .A2 (n_121), .ZN (n_194));
  nr02d1 g4560__5526(.A1 (reset), .A2 (n_120), .ZN (n_193));
  nr02d1 g4561__6783(.A1 (reset), .A2 (n_119), .ZN (n_192));
  nr02d1 g4562__3680(.A1 (reset), .A2 (n_118), .ZN (n_191));
  nr02d1 g4563__1617(.A1 (reset), .A2 (n_134), .ZN (n_190));
  nr02d1 g4564__2802(.A1 (reset), .A2 (n_117), .ZN (n_189));
  nr02d1 g4565__1705(.A1 (reset), .A2 (n_114), .ZN (n_188));
  nr02d1 g4566__5122(.A1 (reset), .A2 (n_115), .ZN (n_187));
  nr02d1 g4567__8246(.A1 (reset), .A2 (n_113), .ZN (n_186));
  nr02d1 g4568__7098(.A1 (reset), .A2 (n_112), .ZN (n_185));
  nr02d1 g4569__6131(.A1 (reset), .A2 (n_111), .ZN (n_184));
  nr02d1 g4570__1881(.A1 (reset), .A2 (n_110), .ZN (n_183));
  nr02d1 g4571__5115(.A1 (reset), .A2 (n_62), .ZN (n_182));
  nr02d1 g4572__7482(.A1 (reset), .A2 (n_61), .ZN (n_181));
  nr02d1 g4573__4733(.A1 (reset), .A2 (n_60), .ZN (n_180));
  nr02d1 g4574__6161(.A1 (reset), .A2 (n_59), .ZN (n_179));
  nr02d1 g4575__9315(.A1 (reset), .A2 (n_133), .ZN (n_178));
  nr02d1 g4577__9945(.A1 (reset), .A2 (n_81), .ZN (n_177));
  nr02d1 g4578__2883(.A1 (reset), .A2 (n_56), .ZN (n_176));
  nr02d1 g4579__2346(.A1 (reset), .A2 (n_132), .ZN (n_175));
  nr02d1 g4580__1666(.A1 (reset), .A2 (n_55), .ZN (n_174));
  nr02d1 g4581__7410(.A1 (reset), .A2 (n_54), .ZN (n_173));
  nr02d1 g4582__6417(.A1 (reset), .A2 (n_53), .ZN (n_172));
  nr02d1 g4583__5477(.A1 (reset), .A2 (n_131), .ZN (n_171));
  nr02d1 g4584__2398(.A1 (reset), .A2 (n_130), .ZN (n_170));
  nr02d1 g4585__5107(.A1 (reset), .A2 (n_52), .ZN (n_169));
  nr02d1 g4586__6260(.A1 (reset), .A2 (n_51), .ZN (n_168));
  nr02d1 g4587__4319(.A1 (reset), .A2 (n_129), .ZN (n_167));
  nr02d1 g4588__8428(.A1 (reset), .A2 (n_128), .ZN (n_166));
  nr02d1 g4589__5526(.A1 (reset), .A2 (n_127), .ZN (n_165));
  nr02d1 g4590__6783(.A1 (reset), .A2 (n_126), .ZN (n_164));
  nr02d1 g4591__3680(.A1 (reset), .A2 (n_125), .ZN (n_163));
  nr02d1 g4592__1617(.A1 (reset), .A2 (n_124), .ZN (n_162));
  nr02d1 g4593__2802(.A1 (reset), .A2 (n_123), .ZN (n_161));
  nr02d1 g4594__1705(.A1 (reset), .A2 (n_122), .ZN (n_160));
  nr02d1 g4595__5122(.A1 (reset), .A2 (n_85), .ZN (n_159));
  nr02d1 g4596__8246(.A1 (reset), .A2 (n_84), .ZN (n_158));
  nr02d1 g4597__7098(.A1 (reset), .A2 (n_83), .ZN (n_157));
  nr02d1 g4598__6131(.A1 (reset), .A2 (n_57), .ZN (n_156));
  nr02d1 g4599__1881(.A1 (reset), .A2 (n_82), .ZN (n_155));
  nr02d1 g4600__5115(.A1 (reset), .A2 (n_109), .ZN (n_154));
  nr02d1 g4601__7482(.A1 (reset), .A2 (n_80), .ZN (n_153));
  nr02d1 g4602__4733(.A1 (reset), .A2 (n_79), .ZN (n_152));
  nr02d1 g4603__6161(.A1 (reset), .A2 (n_78), .ZN (n_151));
  nr02d1 g4604__9315(.A1 (reset), .A2 (n_77), .ZN (n_150));
  nr02d1 g4605__9945(.A1 (reset), .A2 (n_76), .ZN (n_149));
  nr02d1 g4606__2883(.A1 (reset), .A2 (n_75), .ZN (n_148));
  nr02d1 g4607__2346(.A1 (reset), .A2 (n_74), .ZN (n_147));
  nr02d1 g4608__1666(.A1 (reset), .A2 (n_108), .ZN (n_146));
  nr02d1 g4609__7410(.A1 (reset), .A2 (n_107), .ZN (n_145));
  nr02d1 g4610__6417(.A1 (reset), .A2 (n_106), .ZN (n_144));
  nr02d1 g4611__5477(.A1 (reset), .A2 (n_105), .ZN (n_143));
  nr02d1 g4612__2398(.A1 (reset), .A2 (n_104), .ZN (n_142));
  nr02d1 g4613__5107(.A1 (reset), .A2 (n_103), .ZN (n_141));
  nr02d1 g4614__6260(.A1 (reset), .A2 (n_102), .ZN (n_140));
  nr02d1 g4615__4319(.A1 (reset), .A2 (n_101), .ZN (n_139));
  nr02d1 g4616__8428(.A1 (reset), .A2 (n_100), .ZN (n_138));
  nr02d1 g4617__5526(.A1 (reset), .A2 (n_99), .ZN (n_137));
  nr02d1 g4618__6783(.A1 (reset), .A2 (n_50), .ZN (n_136));
  aoi311d1 g4619__3680(.A (n_28), .B (n_25), .C1 (n_6), .C2 (n_0), .C3
       (start_buf), .ZN (n_135));
  aoi22d1 g4620__1617(.A1 (n_31), .A2 (Plaintxt_buf[1]), .B1 (n_30),
       .B2 (data[21]), .ZN (n_134));
  aoi22d1 g4621__2802(.A1 (n_28), .A2 (Plaintxt_buf[0]), .B1 (n_29),
       .B2 (data[16]), .ZN (n_133));
  aoi22d1 g4622__1705(.A1 (n_28), .A2 (Plaintxt_buf[1]), .B1 (n_29),
       .B2 (data[17]), .ZN (n_132));
  aoi22d1 g4623__5122(.A1 (n_28), .A2 (Plaintxt_buf[2]), .B1 (n_29),
       .B2 (data[18]), .ZN (n_131));
  aoi22d1 g4624__8246(.A1 (n_28), .A2 (Plaintxt_buf[3]), .B1 (n_29),
       .B2 (data[19]), .ZN (n_130));
  aoi22d1 g4625__7098(.A1 (n_28), .A2 (key_buf[0]), .B1 (n_29), .B2
       (key_out[32]), .ZN (n_129));
  aoi22d1 g4626__6131(.A1 (n_28), .A2 (key_buf[1]), .B1 (n_29), .B2
       (key_out[33]), .ZN (n_128));
  aoi22d1 g4627__1881(.A1 (n_28), .A2 (key_buf[2]), .B1 (n_29), .B2
       (key_out[34]), .ZN (n_127));
  aoi22d1 g4628__5115(.A1 (n_28), .A2 (key_buf[3]), .B1 (n_29), .B2
       (key_out[35]), .ZN (n_126));
  aoi22d1 g4629__7482(.A1 (n_28), .A2 (key_buf[4]), .B1 (n_29), .B2
       (key_out[36]), .ZN (n_125));
  aoi22d1 g4630__4733(.A1 (n_28), .A2 (key_buf[5]), .B1 (n_29), .B2
       (key_out[37]), .ZN (n_124));
  aoi22d1 g4631__6161(.A1 (n_28), .A2 (key_buf[6]), .B1 (n_29), .B2
       (key_out[38]), .ZN (n_123));
  aoi22d1 g4632__9315(.A1 (n_28), .A2 (key_buf[7]), .B1 (n_29), .B2
       (key_out[39]), .ZN (n_122));
  aoi22d1 g4633__9945(.A1 (n_31), .A2 (key_buf[4]), .B1 (n_30), .B2
       (key_out[44]), .ZN (n_121));
  aoi22d1 g4634__2883(.A1 (n_31), .A2 (key_buf[5]), .B1 (n_30), .B2
       (key_out[45]), .ZN (n_120));
  aoi22d1 g4635__2346(.A1 (n_31), .A2 (key_buf[6]), .B1 (n_30), .B2
       (key_out[46]), .ZN (n_119));
  aoi22d1 g4636__1666(.A1 (n_31), .A2 (key_buf[7]), .B1 (n_30), .B2
       (key_out[47]), .ZN (n_118));
  aoi22d1 g4637__7410(.A1 (n_31), .A2 (Plaintxt_buf[0]), .B1 (n_30),
       .B2 (data[20]), .ZN (n_117));
  aoi21d1 g4638__6417(.A (reset), .B1 (n_32), .B2 (n_2), .ZN (n_116));
  aoi22d1 g4639__5477(.A1 (n_31), .A2 (Plaintxt_buf[3]), .B1 (n_30),
       .B2 (data[23]), .ZN (n_115));
  aoi22d1 g4640__2398(.A1 (n_31), .A2 (Plaintxt_buf[2]), .B1 (n_30),
       .B2 (data[22]), .ZN (n_114));
  aoi22d1 g4641__5107(.A1 (n_31), .A2 (key_buf[0]), .B1 (n_30), .B2
       (key_out[40]), .ZN (n_113));
  aoi22d1 g4642__6260(.A1 (n_31), .A2 (key_buf[1]), .B1 (n_30), .B2
       (key_out[41]), .ZN (n_112));
  aoi22d1 g4643__4319(.A1 (n_31), .A2 (key_buf[2]), .B1 (n_30), .B2
       (key_out[42]), .ZN (n_111));
  aoi22d1 g4644__8428(.A1 (n_31), .A2 (key_buf[3]), .B1 (n_30), .B2
       (key_out[43]), .ZN (n_110));
  aoi22d1 g4645__5526(.A1 (n_33), .A2 (Plaintxt_buf[0]), .B1 (n_32),
       .B2 (data[4]), .ZN (n_109));
  aoi22d1 g4646__6783(.A1 (n_33), .A2 (Plaintxt_buf[1]), .B1 (n_32),
       .B2 (data[5]), .ZN (n_108));
  aoi22d1 g4647__3680(.A1 (n_33), .A2 (Plaintxt_buf[2]), .B1 (n_32),
       .B2 (data[6]), .ZN (n_107));
  aoi22d1 g4648__1617(.A1 (n_33), .A2 (Plaintxt_buf[3]), .B1 (n_32),
       .B2 (data[7]), .ZN (n_106));
  aoi22d1 g4649__2802(.A1 (n_33), .A2 (key_buf[0]), .B1 (n_32), .B2
       (key_out[8]), .ZN (n_105));
  aoi22d1 g4650__1705(.A1 (n_33), .A2 (key_buf[1]), .B1 (n_32), .B2
       (key_out[9]), .ZN (n_104));
  aoi22d1 g4651__5122(.A1 (n_33), .A2 (key_buf[2]), .B1 (n_32), .B2
       (key_out[10]), .ZN (n_103));
  aoi22d1 g4652__8246(.A1 (n_33), .A2 (key_buf[3]), .B1 (n_32), .B2
       (key_out[11]), .ZN (n_102));
  aoi22d1 g4653__7098(.A1 (n_33), .A2 (key_buf[4]), .B1 (n_32), .B2
       (key_out[12]), .ZN (n_101));
  aoi22d1 g4654__6131(.A1 (n_33), .A2 (key_buf[5]), .B1 (n_32), .B2
       (key_out[13]), .ZN (n_100));
  aoi22d1 g4655__1881(.A1 (n_33), .A2 (key_buf[6]), .B1 (n_32), .B2
       (key_out[14]), .ZN (n_99));
  aoi22d1 g4668__5115(.A1 (n_25), .A2 (Plaintxt_buf[0]), .B1 (n_24),
       .B2 (data[24]), .ZN (n_98));
  aoi22d1 g4669__7482(.A1 (n_23), .A2 (Plaintxt_buf[0]), .B1 (n_22),
       .B2 (data[8]), .ZN (n_97));
  aoi22d1 g4670__4733(.A1 (n_23), .A2 (Plaintxt_buf[1]), .B1 (n_22),
       .B2 (data[9]), .ZN (n_96));
  aoi22d1 g4671__6161(.A1 (n_23), .A2 (Plaintxt_buf[2]), .B1 (n_22),
       .B2 (data[10]), .ZN (n_95));
  aoi22d1 g4672__9315(.A1 (n_23), .A2 (Plaintxt_buf[3]), .B1 (n_22),
       .B2 (data[11]), .ZN (n_94));
  aoi22d1 g4673__9945(.A1 (n_23), .A2 (key_buf[0]), .B1 (n_22), .B2
       (key_out[16]), .ZN (n_93));
  aoi22d1 g4674__2883(.A1 (n_23), .A2 (key_buf[1]), .B1 (n_22), .B2
       (key_out[17]), .ZN (n_92));
  aoi22d1 g4675__2346(.A1 (n_23), .A2 (key_buf[2]), .B1 (n_22), .B2
       (key_out[18]), .ZN (n_91));
  aoi22d1 g4676__1666(.A1 (n_23), .A2 (key_buf[3]), .B1 (n_22), .B2
       (key_out[19]), .ZN (n_90));
  aoi22d1 g4677__7410(.A1 (n_23), .A2 (key_buf[4]), .B1 (n_22), .B2
       (key_out[20]), .ZN (n_89));
  aoi22d1 g4678__6417(.A1 (n_23), .A2 (key_buf[5]), .B1 (n_22), .B2
       (key_out[21]), .ZN (n_88));
  aoi22d1 g4679__5477(.A1 (n_23), .A2 (key_buf[6]), .B1 (n_22), .B2
       (key_out[22]), .ZN (n_87));
  aoi22d1 g4680__2398(.A1 (n_23), .A2 (key_buf[7]), .B1 (n_22), .B2
       (key_out[23]), .ZN (n_86));
  aoi22d1 g4681__5107(.A1 (n_34), .A2 (Plaintxt_buf[0]), .B1 (n_35),
       .B2 (data[28]), .ZN (n_85));
  aoi22d1 g4682__6260(.A1 (n_34), .A2 (Plaintxt_buf[1]), .B1 (n_35),
       .B2 (data[29]), .ZN (n_84));
  aoi22d1 g4683__4319(.A1 (n_34), .A2 (Plaintxt_buf[2]), .B1 (n_35),
       .B2 (data[30]), .ZN (n_83));
  aoi22d1 g4684__8428(.A1 (n_34), .A2 (key_buf[0]), .B1 (n_35), .B2
       (key_out[56]), .ZN (n_82));
  aoi22d1 g4685__5526(.A1 (n_34), .A2 (Plaintxt_buf[3]), .B1 (n_35),
       .B2 (data[31]), .ZN (n_81));
  aoi22d1 g4686__6783(.A1 (n_34), .A2 (key_buf[1]), .B1 (n_35), .B2
       (key_out[57]), .ZN (n_80));
  aoi22d1 g4687__3680(.A1 (n_34), .A2 (key_buf[2]), .B1 (n_35), .B2
       (key_out[58]), .ZN (n_79));
  aoi22d1 g4688__1617(.A1 (n_34), .A2 (key_buf[3]), .B1 (n_35), .B2
       (key_out[59]), .ZN (n_78));
  aoi22d1 g4689__2802(.A1 (n_34), .A2 (key_buf[4]), .B1 (n_35), .B2
       (key_out[60]), .ZN (n_77));
  aoi22d1 g4690__1705(.A1 (n_34), .A2 (key_buf[5]), .B1 (n_35), .B2
       (key_out[61]), .ZN (n_76));
  aoi22d1 g4691__5122(.A1 (n_34), .A2 (key_buf[6]), .B1 (n_35), .B2
       (key_out[62]), .ZN (n_75));
  aoi22d1 g4692__8246(.A1 (n_34), .A2 (key_buf[7]), .B1 (n_35), .B2
       (key_out[63]), .ZN (n_74));
  aoi22d1 g4693__7098(.A1 (n_25), .A2 (Plaintxt_buf[2]), .B1 (n_24),
       .B2 (data[26]), .ZN (n_73));
  aoi22d1 g4694__6131(.A1 (n_25), .A2 (Plaintxt_buf[1]), .B1 (n_24),
       .B2 (data[25]), .ZN (n_72));
  aoi22d1 g4695__1881(.A1 (n_25), .A2 (Plaintxt_buf[3]), .B1 (n_24),
       .B2 (data[27]), .ZN (n_71));
  aoi22d1 g4696__5115(.A1 (n_25), .A2 (key_buf[0]), .B1 (n_24), .B2
       (key_out[48]), .ZN (n_70));
  aoi22d1 g4697__7482(.A1 (n_25), .A2 (key_buf[1]), .B1 (n_24), .B2
       (key_out[49]), .ZN (n_69));
  aoi22d1 g4698__4733(.A1 (n_25), .A2 (key_buf[3]), .B1 (n_24), .B2
       (key_out[51]), .ZN (n_68));
  aoi22d1 g4699__6161(.A1 (n_25), .A2 (key_buf[4]), .B1 (n_24), .B2
       (key_out[52]), .ZN (n_67));
  aoi22d1 g4700__9315(.A1 (n_25), .A2 (key_buf[5]), .B1 (n_24), .B2
       (key_out[53]), .ZN (n_66));
  aoi22d1 g4701__9945(.A1 (n_25), .A2 (key_buf[6]), .B1 (n_24), .B2
       (key_out[54]), .ZN (n_65));
  aoi22d1 g4702__2883(.A1 (n_25), .A2 (key_buf[7]), .B1 (n_24), .B2
       (key_out[55]), .ZN (n_64));
  aoi22d1 g4703__2346(.A1 (n_25), .A2 (key_buf[2]), .B1 (n_24), .B2
       (key_out[50]), .ZN (n_63));
  aoi22d1 g4704__1666(.A1 (n_26), .A2 (Plaintxt_buf[0]), .B1 (n_27),
       .B2 (data[12]), .ZN (n_62));
  aoi22d1 g4705__7410(.A1 (n_26), .A2 (Plaintxt_buf[1]), .B1 (n_27),
       .B2 (data[13]), .ZN (n_61));
  aoi22d1 g4706__6417(.A1 (n_26), .A2 (Plaintxt_buf[2]), .B1 (n_27),
       .B2 (data[14]), .ZN (n_60));
  aoi22d1 g4707__5477(.A1 (n_26), .A2 (Plaintxt_buf[3]), .B1 (n_27),
       .B2 (data[15]), .ZN (n_59));
  aoi22d1 g4708__2398(.A1 (n_26), .A2 (key_buf[0]), .B1 (n_27), .B2
       (key_out[24]), .ZN (n_58));
  aoi22d1 g4709__5107(.A1 (n_26), .A2 (key_buf[1]), .B1 (n_27), .B2
       (key_out[25]), .ZN (n_57));
  aoi22d1 g4710__6260(.A1 (n_26), .A2 (key_buf[2]), .B1 (n_27), .B2
       (key_out[26]), .ZN (n_56));
  aoi22d1 g4711__4319(.A1 (n_26), .A2 (key_buf[3]), .B1 (n_27), .B2
       (key_out[27]), .ZN (n_55));
  aoi22d1 g4712__8428(.A1 (n_26), .A2 (key_buf[4]), .B1 (n_27), .B2
       (key_out[28]), .ZN (n_54));
  aoi22d1 g4713__5526(.A1 (n_26), .A2 (key_buf[5]), .B1 (n_27), .B2
       (key_out[29]), .ZN (n_53));
  aoi22d1 g4714__6783(.A1 (n_26), .A2 (key_buf[6]), .B1 (n_27), .B2
       (key_out[30]), .ZN (n_52));
  aoi22d1 g4715__3680(.A1 (n_26), .A2 (key_buf[7]), .B1 (n_27), .B2
       (key_out[31]), .ZN (n_51));
  aoi22d1 g4716__1617(.A1 (n_33), .A2 (key_buf[7]), .B1 (n_32), .B2
       (key_out[15]), .ZN (n_50));
  nr02d1 g4717__2802(.A1 (reset), .A2 (n_15), .ZN (n_49));
  nr02d1 g4718__1705(.A1 (reset), .A2 (n_21), .ZN (n_48));
  nr02d1 g4719__5122(.A1 (reset), .A2 (n_12), .ZN (n_47));
  nr02d1 g4720__8246(.A1 (reset), .A2 (n_17), .ZN (n_46));
  nr02d1 g4721__7098(.A1 (reset), .A2 (n_14), .ZN (n_45));
  nr02d1 g4722__6131(.A1 (reset), .A2 (n_16), .ZN (n_44));
  nr02d1 g4723__1881(.A1 (reset), .A2 (n_13), .ZN (n_43));
  nr02d1 g4724__5115(.A1 (n_34), .A2 (n_25), .ZN (n_42));
  nr02d1 g4725__7482(.A1 (reset), .A2 (n_11), .ZN (n_41));
  nr02d1 g4726__4733(.A1 (reset), .A2 (n_20), .ZN (n_40));
  nr02d1 g4727__6161(.A1 (reset), .A2 (n_19), .ZN (n_39));
  nr02d1 g4728__9315(.A1 (reset), .A2 (n_10), .ZN (n_38));
  nr02d1 g4729__9945(.A1 (n_31), .A2 (n_23), .ZN (n_37));
  nr02d1 g4730__2883(.A1 (reset), .A2 (n_18), .ZN (n_36));
  inv0d1 g4731(.I (n_35), .ZN (n_34));
  inv0d1 g4732(.I (n_33), .ZN (n_32));
  inv0d1 g4733(.I (n_31), .ZN (n_30));
  inv0d1 g4734(.I (n_29), .ZN (n_28));
  inv0d1 g4735(.I (n_27), .ZN (n_26));
  inv0d1 g4736(.I (n_25), .ZN (n_24));
  inv0d1 g4737(.I (n_23), .ZN (n_22));
  aoi22d1 g4738__2346(.A1 (n_3), .A2 (key_buf[4]), .B1 (n_2), .B2
       (key_out[4]), .ZN (n_21));
  aoi22d1 g4739__1666(.A1 (n_3), .A2 (key_buf[3]), .B1 (n_2), .B2
       (key_out[3]), .ZN (n_20));
  nd02d1 g4740__7410(.A1 (n_6), .A2 (state[0]), .ZN (n_35));
  an02d1 g4741__6417(.A1 (n_9), .A2 (state[0]), .Z (n_33));
  nr02d2 g4742__5477(.A1 (n_8), .A2 (n_0), .ZN (n_31));
  nd02d1 g4743__2398(.A1 (n_7), .A2 (n_0), .ZN (n_29));
  nd02d1 g4744__5107(.A1 (n_7), .A2 (state[0]), .ZN (n_27));
  nr02d2 g4745__6260(.A1 (n_8), .A2 (state[0]), .ZN (n_25));
  an02d1 g4746__4319(.A1 (n_9), .A2 (n_0), .Z (n_23));
  aoi22d1 g4747__8428(.A1 (n_3), .A2 (Plaintxt_buf[3]), .B1 (n_2), .B2
       (data[3]), .ZN (n_19));
  aoi22d1 g4748__5526(.A1 (n_3), .A2 (key_buf[1]), .B1 (n_2), .B2
       (key_out[1]), .ZN (n_18));
  aoi22d1 g4749__6783(.A1 (n_3), .A2 (key_buf[2]), .B1 (n_2), .B2
       (key_out[2]), .ZN (n_17));
  aoi22d1 g4750__3680(.A1 (n_3), .A2 (key_buf[6]), .B1 (n_2), .B2
       (key_out[6]), .ZN (n_16));
  aoi22d1 g4751__1617(.A1 (n_3), .A2 (key_buf[7]), .B1 (n_2), .B2
       (key_out[7]), .ZN (n_15));
  aoi22d1 g4752__2802(.A1 (n_3), .A2 (key_buf[5]), .B1 (n_2), .B2
       (key_out[5]), .ZN (n_14));
  aoi22d1 g4753__1705(.A1 (n_3), .A2 (Plaintxt_buf[2]), .B1 (n_2), .B2
       (data[2]), .ZN (n_13));
  aoi22d1 g4754__5122(.A1 (n_3), .A2 (key_buf[0]), .B1 (n_2), .B2
       (key_out[0]), .ZN (n_12));
  aoi22d1 g4755__8246(.A1 (n_3), .A2 (Plaintxt_buf[0]), .B1 (n_2), .B2
       (data[0]), .ZN (n_11));
  aoi22d1 g4756__7098(.A1 (n_3), .A2 (Plaintxt_buf[1]), .B1 (n_2), .B2
       (data[1]), .ZN (n_10));
  nr02d1 g4757__6131(.A1 (n_1), .A2 (n_5), .ZN (n_9));
  nd02d1 g4758__1881(.A1 (n_4), .A2 (state[1]), .ZN (n_8));
  nr02d1 g4759__5115(.A1 (state[1]), .A2 (n_5), .ZN (n_7));
  an02d1 g4760__7482(.A1 (n_4), .A2 (n_1), .Z (n_6));
  nd12d1 g4761__4733(.A1 (state[3]), .A2 (state[2]), .ZN (n_5));
  inv0d1 g4762(.I (n_3), .ZN (n_2));
  nr02d1 g4763__6161(.A1 (state[2]), .A2 (state[3]), .ZN (n_4));
  nr02d2 g4764__9315(.A1 (state[0]), .A2 (n_227), .ZN (n_3));
  dfnrb1 \state_reg[0] (.CP (clk), .D (n_222), .Q (state[0]), .QN
       (n_0));
  dfnrb1 \state_reg[1] (.CP (clk), .D (n_220), .Q (state[1]), .QN
       (n_1));
endmodule

module output_giver_N32_M4_C8(clk, reset, start, data, cipher, done);
  input clk, reset, start;
  input [31:0] data;
  output [3:0] cipher;
  output done;
  wire clk, reset, start;
  wire [31:0] data;
  wire [3:0] cipher;
  wire done;
  wire [31:0] buffer_reg;
  wire [5:0] i_cur;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_81, n_82;
  wire n_83, n_84, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_153;
  dfnrq1 \cipher_reg[3] (.CP (clk), .D (n_110), .Q (cipher[3]));
  dfnrq1 \cipher_reg[2] (.CP (clk), .D (n_111), .Q (cipher[2]));
  dfnrq1 \cipher_reg[0] (.CP (clk), .D (n_112), .Q (cipher[0]));
  dfnrq1 \cipher_reg[1] (.CP (clk), .D (n_113), .Q (cipher[1]));
  aor22d1 g4640__9945(.A1 (n_107), .A2 (n_101), .B1 (n_102), .B2
       (buffer_reg[29]), .Z (n_113));
  aor22d1 g4641__2883(.A1 (n_106), .A2 (n_101), .B1 (n_102), .B2
       (buffer_reg[28]), .Z (n_112));
  aor22d1 g4642__2346(.A1 (n_109), .A2 (n_101), .B1 (n_102), .B2
       (buffer_reg[30]), .Z (n_111));
  aor22d1 g4643__1666(.A1 (n_108), .A2 (n_101), .B1 (n_102), .B2
       (buffer_reg[31]), .Z (n_110));
  nr04d1 g4644__7410(.A1 (n_89), .A2 (n_90), .A3 (n_92), .A4 (n_95),
       .ZN (n_109));
  nr04d1 g4645__6417(.A1 (n_88), .A2 (n_94), .A3 (n_96), .A4 (n_93),
       .ZN (n_108));
  nr03d1 g4646__5477(.A1 (n_97), .A2 (n_100), .A3 (n_103), .ZN (n_107));
  nr03d1 g4647__2398(.A1 (n_91), .A2 (n_99), .A3 (n_104), .ZN (n_106));
  dfnrq1 done_reg(.CP (clk), .D (n_153), .Q (done));
  oai222d1 g4650__6260(.A1 (n_84), .A2 (buffer_reg[16]), .B1 (n_81),
       .B2 (buffer_reg[12]), .C1 (n_83), .C2 (buffer_reg[20]), .ZN
       (n_104));
  oai222d1 g4651__4319(.A1 (n_83), .A2 (buffer_reg[21]), .B1 (n_77),
       .B2 (buffer_reg[5]), .C1 (n_116), .C2 (buffer_reg[25]), .ZN
       (n_103));
  oai22d1 g4652__8428(.A1 (n_87), .A2 (buffer_reg[1]), .B1 (n_84), .B2
       (buffer_reg[17]), .ZN (n_100));
  oai22d1 g4653__5526(.A1 (n_87), .A2 (buffer_reg[0]), .B1 (n_116), .B2
       (buffer_reg[24]), .ZN (n_99));
  oai22d1 g4655__3680(.A1 (n_115), .A2 (buffer_reg[9]), .B1 (n_81), .B2
       (buffer_reg[13]), .ZN (n_97));
  nr13d1 g4656__1617(.A1 (i_cur[5]), .A2 (reset), .A3 (n_117), .ZN
       (n_102));
  nr03d1 g4657__2802(.A1 (reset), .A2 (i_cur[5]), .A3 (n_5), .ZN
       (n_101));
  oai22d1 g4658__1705(.A1 (n_116), .A2 (buffer_reg[27]), .B1 (n_77),
       .B2 (buffer_reg[7]), .ZN (n_96));
  oai22d1 g4659__5122(.A1 (n_87), .A2 (buffer_reg[2]), .B1 (n_84), .B2
       (buffer_reg[18]), .ZN (n_95));
  oai22d1 g4660__8246(.A1 (n_83), .A2 (buffer_reg[23]), .B1 (n_81), .B2
       (buffer_reg[15]), .ZN (n_94));
  oai22d1 g4661__7098(.A1 (n_87), .A2 (buffer_reg[3]), .B1 (n_84), .B2
       (buffer_reg[19]), .ZN (n_93));
  oai22d1 g4662__6131(.A1 (n_116), .A2 (buffer_reg[26]), .B1 (n_77),
       .B2 (buffer_reg[6]), .ZN (n_92));
  oai22d1 g4663__1881(.A1 (n_115), .A2 (buffer_reg[8]), .B1 (n_77), .B2
       (buffer_reg[4]), .ZN (n_91));
  oai22d1 g4664__5115(.A1 (n_115), .A2 (buffer_reg[10]), .B1 (n_81),
       .B2 (buffer_reg[14]), .ZN (n_90));
  nr02d1 g4665__7482(.A1 (buffer_reg[22]), .A2 (n_83), .ZN (n_89));
  nr02d1 g4666__4733(.A1 (buffer_reg[11]), .A2 (n_115), .ZN (n_88));
  inv0d0 g4667(.I (n_86), .ZN (n_87));
  or02d1 g4668__6161(.A1 (n_114), .A2 (i_cur[4]), .Z (n_115));
  nd12d1 g4669__9315(.A1 (n_114), .A2 (i_cur[4]), .ZN (n_116));
  nr02d1 g4670__9945(.A1 (i_cur[4]), .A2 (n_82), .ZN (n_86));
  inv0d0 g4671(.I (n_5), .ZN (n_117));
  nr02d1 g4672__2883(.A1 (i_cur[4]), .A2 (n_81), .ZN (n_5));
  nd12d1 g4673__2346(.A1 (n_82), .A2 (i_cur[4]), .ZN (n_84));
  nd03d1 g4674__1666(.A1 (n_4), .A2 (i_cur[4]), .A3 (i_cur[3]), .ZN
       (n_83));
  nd12d1 g4675__7410(.A1 (i_cur[3]), .A2 (i_cur[2]), .ZN (n_82));
  nd12d1 g4676__6417(.A1 (i_cur[3]), .A2 (n_4), .ZN (n_81));
  nd02d1 g4677__5477(.A1 (i_cur[3]), .A2 (i_cur[2]), .ZN (n_114));
  nd12d1 g2__2398(.A1 (i_cur[4]), .A2 (n_4), .ZN (n_77));
  dfnrq1 \buffer_reg_reg[0] (.CP (clk), .D (n_59), .Q (buffer_reg[0]));
  dfnrq1 \buffer_reg_reg[1] (.CP (clk), .D (n_64), .Q (buffer_reg[1]));
  dfnrq1 \buffer_reg_reg[2] (.CP (clk), .D (n_62), .Q (buffer_reg[2]));
  dfnrq1 \buffer_reg_reg[3] (.CP (clk), .D (n_57), .Q (buffer_reg[3]));
  dfnrq1 \buffer_reg_reg[4] (.CP (clk), .D (n_40), .Q (buffer_reg[4]));
  dfnrq1 \buffer_reg_reg[5] (.CP (clk), .D (n_52), .Q (buffer_reg[5]));
  dfnrq1 \buffer_reg_reg[6] (.CP (clk), .D (n_49), .Q (buffer_reg[6]));
  dfnrq1 \buffer_reg_reg[7] (.CP (clk), .D (n_44), .Q (buffer_reg[7]));
  dfnrq1 \buffer_reg_reg[8] (.CP (clk), .D (n_42), .Q (buffer_reg[8]));
  dfnrq1 \buffer_reg_reg[9] (.CP (clk), .D (n_41), .Q (buffer_reg[9]));
  dfnrq1 \buffer_reg_reg[10] (.CP (clk), .D (n_55), .Q
       (buffer_reg[10]));
  dfnrq1 \buffer_reg_reg[11] (.CP (clk), .D (n_70), .Q
       (buffer_reg[11]));
  dfnrq1 \buffer_reg_reg[12] (.CP (clk), .D (n_56), .Q
       (buffer_reg[12]));
  dfnrq1 \buffer_reg_reg[13] (.CP (clk), .D (n_69), .Q
       (buffer_reg[13]));
  dfnrq1 \buffer_reg_reg[14] (.CP (clk), .D (n_68), .Q
       (buffer_reg[14]));
  dfnrq1 \buffer_reg_reg[15] (.CP (clk), .D (n_67), .Q
       (buffer_reg[15]));
  dfnrq1 \buffer_reg_reg[16] (.CP (clk), .D (n_66), .Q
       (buffer_reg[16]));
  dfnrq1 \buffer_reg_reg[17] (.CP (clk), .D (n_65), .Q
       (buffer_reg[17]));
  dfnrq1 \buffer_reg_reg[18] (.CP (clk), .D (n_63), .Q
       (buffer_reg[18]));
  dfnrq1 \buffer_reg_reg[19] (.CP (clk), .D (n_61), .Q
       (buffer_reg[19]));
  dfnrq1 \buffer_reg_reg[20] (.CP (clk), .D (n_60), .Q
       (buffer_reg[20]));
  dfnrq1 \buffer_reg_reg[21] (.CP (clk), .D (n_58), .Q
       (buffer_reg[21]));
  dfnrq1 \buffer_reg_reg[22] (.CP (clk), .D (n_71), .Q
       (buffer_reg[22]));
  dfnrq1 \buffer_reg_reg[23] (.CP (clk), .D (n_54), .Q
       (buffer_reg[23]));
  dfnrq1 \buffer_reg_reg[24] (.CP (clk), .D (n_53), .Q
       (buffer_reg[24]));
  dfnrq1 \buffer_reg_reg[25] (.CP (clk), .D (n_51), .Q
       (buffer_reg[25]));
  dfnrq1 \buffer_reg_reg[26] (.CP (clk), .D (n_50), .Q
       (buffer_reg[26]));
  dfnrq1 \buffer_reg_reg[27] (.CP (clk), .D (n_48), .Q
       (buffer_reg[27]));
  dfnrq1 \buffer_reg_reg[28] (.CP (clk), .D (n_47), .Q
       (buffer_reg[28]));
  dfnrq1 \buffer_reg_reg[29] (.CP (clk), .D (n_46), .Q
       (buffer_reg[29]));
  dfnrq1 \buffer_reg_reg[30] (.CP (clk), .D (n_45), .Q
       (buffer_reg[30]));
  dfnrq1 \buffer_reg_reg[31] (.CP (clk), .D (n_43), .Q
       (buffer_reg[31]));
  dfnrq1 \i_cur_reg[3] (.CP (clk), .D (n_75), .Q (i_cur[3]));
  dfnrq1 \i_cur_reg[4] (.CP (clk), .D (n_74), .Q (i_cur[4]));
  nr02d1 g5019__5107(.A1 (i_cur[2]), .A2 (n_72), .ZN (n_76));
  nr02d1 g5020__6260(.A1 (n_24), .A2 (n_72), .ZN (n_75));
  aoi21d1 g5021__4319(.A (n_72), .B1 (n_115), .B2 (n_6), .ZN (n_74));
  aoi21d1 g5022__8428(.A (n_72), .B1 (n_116), .B2 (n_3), .ZN (n_73));
  oai321d1 g5055__5526(.A (n_1), .B1 (n_5), .B2 (n_3), .C1 (start), .C2
       (n_117), .C3 (i_cur[5]), .ZN (n_72));
  nr02d1 g5056__6783(.A1 (n_0), .A2 (n_19), .ZN (n_71));
  nr02d1 g5057__3680(.A1 (n_0), .A2 (n_37), .ZN (n_70));
  nr02d1 g5058__1617(.A1 (n_0), .A2 (n_35), .ZN (n_69));
  nr02d1 g5059__2802(.A1 (n_0), .A2 (n_34), .ZN (n_68));
  nr02d1 g5060__1705(.A1 (n_0), .A2 (n_33), .ZN (n_67));
  nr02d1 g5061__5122(.A1 (n_0), .A2 (n_32), .ZN (n_66));
  nr02d1 g5062__8246(.A1 (n_0), .A2 (n_29), .ZN (n_65));
  nr02d1 g5063__7098(.A1 (n_0), .A2 (n_30), .ZN (n_64));
  nr02d1 g5064__6131(.A1 (n_0), .A2 (n_28), .ZN (n_63));
  nr02d1 g5065__1881(.A1 (n_0), .A2 (n_25), .ZN (n_62));
  nr02d1 g5066__5115(.A1 (n_0), .A2 (n_26), .ZN (n_61));
  nr02d1 g5067__7482(.A1 (n_0), .A2 (n_39), .ZN (n_60));
  nr02d1 g5068__4733(.A1 (n_0), .A2 (n_27), .ZN (n_59));
  nr02d1 g5069__6161(.A1 (n_0), .A2 (n_23), .ZN (n_58));
  nr02d1 g5070__9315(.A1 (n_0), .A2 (n_20), .ZN (n_57));
  nr02d1 g5071__9945(.A1 (n_0), .A2 (n_36), .ZN (n_56));
  nr02d1 g5072__2883(.A1 (n_0), .A2 (n_38), .ZN (n_55));
  nr02d1 g5073__2346(.A1 (n_0), .A2 (n_18), .ZN (n_54));
  nr02d1 g5074__1666(.A1 (n_0), .A2 (n_17), .ZN (n_53));
  nr02d1 g5075__7410(.A1 (n_0), .A2 (n_15), .ZN (n_52));
  nr02d1 g5076__6417(.A1 (n_0), .A2 (n_22), .ZN (n_51));
  nr02d1 g5077__5477(.A1 (n_0), .A2 (n_14), .ZN (n_50));
  nr02d1 g5078__2398(.A1 (n_0), .A2 (n_11), .ZN (n_49));
  nr02d1 g5079__5107(.A1 (n_0), .A2 (n_13), .ZN (n_48));
  nr02d1 g5080__6260(.A1 (n_0), .A2 (n_12), .ZN (n_47));
  nr02d1 g5081__4319(.A1 (n_0), .A2 (n_10), .ZN (n_46));
  nr02d1 g5082__8428(.A1 (n_0), .A2 (n_9), .ZN (n_45));
  nr02d1 g5083__5526(.A1 (n_0), .A2 (n_8), .ZN (n_44));
  nr02d1 g5084__6783(.A1 (n_0), .A2 (n_16), .ZN (n_43));
  nr02d1 g5085__3680(.A1 (n_0), .A2 (n_21), .ZN (n_42));
  nr02d1 g5086__1617(.A1 (n_0), .A2 (n_7), .ZN (n_41));
  nr02d1 g5087__2802(.A1 (n_0), .A2 (n_31), .ZN (n_40));
  aoi22d1 g5088__1705(.A1 (n_2), .A2 (buffer_reg[20]), .B1 (start), .B2
       (data[20]), .ZN (n_39));
  aoi22d1 g5089__5122(.A1 (n_2), .A2 (buffer_reg[10]), .B1 (start), .B2
       (data[10]), .ZN (n_38));
  aoi22d1 g5090__8246(.A1 (n_2), .A2 (buffer_reg[11]), .B1 (start), .B2
       (data[11]), .ZN (n_37));
  aoi22d1 g5091__7098(.A1 (n_2), .A2 (buffer_reg[12]), .B1 (start), .B2
       (data[12]), .ZN (n_36));
  aoi22d1 g5092__6131(.A1 (n_2), .A2 (buffer_reg[13]), .B1 (start), .B2
       (data[13]), .ZN (n_35));
  aoi22d1 g5093__1881(.A1 (n_2), .A2 (buffer_reg[14]), .B1 (start), .B2
       (data[14]), .ZN (n_34));
  aoi22d1 g5094__5115(.A1 (n_2), .A2 (buffer_reg[15]), .B1 (start), .B2
       (data[15]), .ZN (n_33));
  aoi22d1 g5095__7482(.A1 (n_2), .A2 (buffer_reg[16]), .B1 (start), .B2
       (data[16]), .ZN (n_32));
  aoi22d1 g5096__4733(.A1 (n_2), .A2 (buffer_reg[4]), .B1 (start), .B2
       (data[4]), .ZN (n_31));
  aoi22d1 g5097__6161(.A1 (n_2), .A2 (buffer_reg[1]), .B1 (start), .B2
       (data[1]), .ZN (n_30));
  aoi22d1 g5098__9315(.A1 (n_2), .A2 (buffer_reg[17]), .B1 (start), .B2
       (data[17]), .ZN (n_29));
  aoi22d1 g5099__9945(.A1 (n_2), .A2 (buffer_reg[18]), .B1 (start), .B2
       (data[18]), .ZN (n_28));
  aoi22d1 g5100__2883(.A1 (n_2), .A2 (buffer_reg[0]), .B1 (start), .B2
       (data[0]), .ZN (n_27));
  aoi22d1 g5101__2346(.A1 (n_2), .A2 (buffer_reg[19]), .B1 (start), .B2
       (data[19]), .ZN (n_26));
  aoi22d1 g5102__1666(.A1 (n_2), .A2 (buffer_reg[2]), .B1 (start), .B2
       (data[2]), .ZN (n_25));
  aoim22d1 g5103__7410(.A1 (i_cur[3]), .A2 (n_4), .B1 (i_cur[3]), .B2
       (n_4), .Z (n_24));
  aoi22d1 g5104__6417(.A1 (n_2), .A2 (buffer_reg[21]), .B1 (start), .B2
       (data[21]), .ZN (n_23));
  aoi22d1 g5105__5477(.A1 (n_2), .A2 (buffer_reg[25]), .B1 (start), .B2
       (data[25]), .ZN (n_22));
  aoi22d1 g5106__2398(.A1 (n_2), .A2 (buffer_reg[8]), .B1 (start), .B2
       (data[8]), .ZN (n_21));
  aoi22d1 g5107__5107(.A1 (n_2), .A2 (buffer_reg[3]), .B1 (start), .B2
       (data[3]), .ZN (n_20));
  aoi22d1 g5108__6260(.A1 (n_2), .A2 (buffer_reg[22]), .B1 (start), .B2
       (data[22]), .ZN (n_19));
  aoi22d1 g5109__4319(.A1 (n_2), .A2 (buffer_reg[23]), .B1 (start), .B2
       (data[23]), .ZN (n_18));
  aoi22d1 g5110__8428(.A1 (n_2), .A2 (buffer_reg[24]), .B1 (start), .B2
       (data[24]), .ZN (n_17));
  aoi22d1 g5111__5526(.A1 (n_2), .A2 (buffer_reg[31]), .B1 (start), .B2
       (data[31]), .ZN (n_16));
  aoi22d1 g5112__6783(.A1 (n_2), .A2 (buffer_reg[5]), .B1 (start), .B2
       (data[5]), .ZN (n_15));
  aoi22d1 g5113__3680(.A1 (n_2), .A2 (buffer_reg[26]), .B1 (start), .B2
       (data[26]), .ZN (n_14));
  aoi22d1 g5114__1617(.A1 (n_2), .A2 (buffer_reg[27]), .B1 (start), .B2
       (data[27]), .ZN (n_13));
  aoi22d1 g5115__2802(.A1 (n_2), .A2 (buffer_reg[28]), .B1 (start), .B2
       (data[28]), .ZN (n_12));
  aoi22d1 g5116__1705(.A1 (n_2), .A2 (buffer_reg[6]), .B1 (start), .B2
       (data[6]), .ZN (n_11));
  aoi22d1 g5117__5122(.A1 (n_2), .A2 (buffer_reg[29]), .B1 (start), .B2
       (data[29]), .ZN (n_10));
  aoi22d1 g5118__8246(.A1 (n_2), .A2 (buffer_reg[30]), .B1 (start), .B2
       (data[30]), .ZN (n_9));
  aoi22d1 g5119__7098(.A1 (n_2), .A2 (buffer_reg[7]), .B1 (start), .B2
       (data[7]), .ZN (n_8));
  aoi22d1 g5120__6131(.A1 (n_2), .A2 (buffer_reg[9]), .B1 (start), .B2
       (data[9]), .ZN (n_7));
  nd02d1 g5121__1881(.A1 (i_cur[4]), .A2 (n_114), .ZN (n_6));
  invbd2 g5127(.I (start), .ZN (n_2));
  invbd2 drc_bufs5133(.I (n_1), .ZN (n_0));
  inv0d0 drc_bufs5134(.I (reset), .ZN (n_1));
  nr23d1 g2(.A1 (n_86), .A2 (i_cur[5]), .A3 (reset), .ZN (n_153));
  dfnrb1 \i_cur_reg[2] (.CP (clk), .D (n_76), .Q (i_cur[2]), .QN (n_4));
  dfnrb1 \i_cur_reg[5] (.CP (clk), .D (n_73), .Q (i_cur[5]), .QN (n_3));
endmodule

module encrypt(clk, reset, start, round_key, plain_text, cipher_text,
     done);
  input clk, reset, start;
  input [15:0] round_key;
  input [31:0] plain_text;
  output [31:0] cipher_text;
  output done;
  wire clk, reset, start;
  wire [15:0] round_key;
  wire [31:0] plain_text;
  wire [31:0] cipher_text;
  wire done;
  wire [5:0] i_cur;
  wire [15:0] y_cur;
  wire [15:0] x_cur;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_255;
  an02d4 g1945__5115(.A1 (n_168), .A2 (n_255), .Z (done));
  inv0d0 g1946(.I (n_168), .ZN (n_170));
  nr02d1 g1947__7482(.A1 (i_cur[0]), .A2 (n_169), .ZN (n_168));
  or04d1 g1948__4733(.A1 (i_cur[3]), .A2 (i_cur[1]), .A3 (i_cur[2]),
       .A4 (i_cur[4]), .Z (n_169));
  an02d1 g1949__6161(.A1 (n_255), .A2 (y_cur[10]), .Z
       (cipher_text[10]));
  an02d1 g1950__9315(.A1 (n_255), .A2 (x_cur[12]), .Z
       (cipher_text[28]));
  an02d1 g1951__9945(.A1 (n_255), .A2 (y_cur[0]), .Z (cipher_text[0]));
  an02d1 g1952__2883(.A1 (n_255), .A2 (x_cur[8]), .Z (cipher_text[24]));
  an02d1 g1953__2346(.A1 (n_255), .A2 (x_cur[0]), .Z (cipher_text[16]));
  an02d1 g1954__1666(.A1 (n_255), .A2 (x_cur[14]), .Z
       (cipher_text[30]));
  an02d1 g1955__7410(.A1 (n_255), .A2 (y_cur[15]), .Z
       (cipher_text[15]));
  an02d1 g1956__6417(.A1 (n_255), .A2 (x_cur[7]), .Z (cipher_text[23]));
  an02d1 g1957__5477(.A1 (n_255), .A2 (y_cur[14]), .Z
       (cipher_text[14]));
  an02d1 g1958__2398(.A1 (n_255), .A2 (y_cur[13]), .Z
       (cipher_text[13]));
  an02d1 g1959__5107(.A1 (n_255), .A2 (x_cur[11]), .Z
       (cipher_text[27]));
  an02d1 g1960__6260(.A1 (n_255), .A2 (x_cur[6]), .Z (cipher_text[22]));
  an02d1 g1961__4319(.A1 (n_255), .A2 (y_cur[12]), .Z
       (cipher_text[12]));
  an02d1 g1962__8428(.A1 (n_255), .A2 (y_cur[11]), .Z
       (cipher_text[11]));
  an02d1 g1963__5526(.A1 (n_255), .A2 (x_cur[5]), .Z (cipher_text[21]));
  an02d1 g1964__6783(.A1 (n_255), .A2 (x_cur[15]), .Z
       (cipher_text[31]));
  an02d1 g1965__3680(.A1 (n_255), .A2 (y_cur[1]), .Z (cipher_text[1]));
  an02d1 g1966__1617(.A1 (n_255), .A2 (x_cur[13]), .Z
       (cipher_text[29]));
  an02d1 g1967__2802(.A1 (n_255), .A2 (x_cur[10]), .Z
       (cipher_text[26]));
  an02d1 g1968__1705(.A1 (n_255), .A2 (x_cur[4]), .Z (cipher_text[20]));
  an02d1 g1969__5122(.A1 (n_255), .A2 (y_cur[8]), .Z (cipher_text[8]));
  an02d1 g1970__8246(.A1 (n_255), .A2 (y_cur[7]), .Z (cipher_text[7]));
  an02d1 g1971__7098(.A1 (n_255), .A2 (x_cur[3]), .Z (cipher_text[19]));
  an02d1 g1972__6131(.A1 (n_255), .A2 (y_cur[6]), .Z (cipher_text[6]));
  an02d1 g1973__1881(.A1 (n_255), .A2 (y_cur[5]), .Z (cipher_text[5]));
  an02d1 g1974__5115(.A1 (n_255), .A2 (x_cur[9]), .Z (cipher_text[25]));
  an02d1 g1975__7482(.A1 (n_255), .A2 (x_cur[2]), .Z (cipher_text[18]));
  an02d1 g1976__4733(.A1 (n_255), .A2 (y_cur[4]), .Z (cipher_text[4]));
  an02d1 g1977__6161(.A1 (n_255), .A2 (y_cur[3]), .Z (cipher_text[3]));
  an02d1 g1978__9315(.A1 (n_255), .A2 (x_cur[1]), .Z (cipher_text[17]));
  an02d1 g1979__9945(.A1 (n_255), .A2 (y_cur[2]), .Z (cipher_text[2]));
  an02d1 g1980__2883(.A1 (n_255), .A2 (y_cur[9]), .Z (cipher_text[9]));
  dfnrq1 \i_cur_reg[1] (.CP (clk), .D (n_157), .Q (i_cur[1]));
  dfnrq1 \i_cur_reg[2] (.CP (clk), .D (n_160), .Q (i_cur[2]));
  dfnrq1 \i_cur_reg[3] (.CP (clk), .D (n_163), .Q (i_cur[3]));
  dfnrq1 \i_cur_reg[4] (.CP (clk), .D (n_166), .Q (i_cur[4]));
  dfnrq1 \y_cur_reg[0] (.CP (clk), .D (n_137), .Q (y_cur[0]));
  dfnrq1 \y_cur_reg[1] (.CP (clk), .D (n_128), .Q (y_cur[1]));
  dfnrq1 \y_cur_reg[2] (.CP (clk), .D (n_127), .Q (y_cur[2]));
  dfnrq1 \y_cur_reg[3] (.CP (clk), .D (n_126), .Q (y_cur[3]));
  dfnrq1 \y_cur_reg[4] (.CP (clk), .D (n_136), .Q (y_cur[4]));
  dfnrq1 \y_cur_reg[5] (.CP (clk), .D (n_125), .Q (y_cur[5]));
  dfnrq1 \y_cur_reg[6] (.CP (clk), .D (n_135), .Q (y_cur[6]));
  dfnrq1 \y_cur_reg[7] (.CP (clk), .D (n_124), .Q (y_cur[7]));
  dfnrq1 \y_cur_reg[8] (.CP (clk), .D (n_138), .Q (y_cur[8]));
  dfnrq1 \y_cur_reg[9] (.CP (clk), .D (n_133), .Q (y_cur[9]));
  dfnrq1 \y_cur_reg[10] (.CP (clk), .D (n_132), .Q (y_cur[10]));
  dfnrq1 \y_cur_reg[11] (.CP (clk), .D (n_131), .Q (y_cur[11]));
  dfnrq1 \y_cur_reg[12] (.CP (clk), .D (n_134), .Q (y_cur[12]));
  dfnrq1 \y_cur_reg[13] (.CP (clk), .D (n_123), .Q (y_cur[13]));
  dfnrq1 \y_cur_reg[14] (.CP (clk), .D (n_130), .Q (y_cur[14]));
  dfnrq1 \y_cur_reg[15] (.CP (clk), .D (n_129), .Q (y_cur[15]));
  aoim21d1 g3730__2346(.A (n_46), .B1 (n_164), .B2 (n_255), .ZN
       (n_167));
  an02d1 g3731__1666(.A1 (n_165), .A2 (n_47), .Z (n_166));
  ah01d1 g3732__7410(.A (n_161), .B (i_cur[4]), .CO (n_164), .S
       (n_165));
  an02d1 g3734__6417(.A1 (n_162), .A2 (n_47), .Z (n_163));
  ah01d1 g3735__5477(.A (n_158), .B (i_cur[3]), .CO (n_161), .S
       (n_162));
  an02d1 g3737__2398(.A1 (n_159), .A2 (n_47), .Z (n_160));
  ah01d1 g3738__5107(.A (n_139), .B (i_cur[2]), .CO (n_158), .S
       (n_159));
  aor21d1 g3748__6260(.A (reset), .B1 (n_140), .B2 (n_47), .Z (n_157));
  oai222d1 g3773__4319(.A1 (n_100), .A2 (n_65), .B1 (n_86), .B2 (n_1),
       .C1 (n_99), .C2 (n_26), .ZN (n_156));
  oai222d1 g3774__8428(.A1 (n_111), .A2 (n_65), .B1 (n_86), .B2 (n_4),
       .C1 (n_99), .C2 (n_31), .ZN (n_155));
  oai222d1 g3775__5526(.A1 (n_113), .A2 (n_65), .B1 (n_86), .B2 (n_7),
       .C1 (n_99), .C2 (n_25), .ZN (n_154));
  oai222d1 g3776__6783(.A1 (n_112), .A2 (n_65), .B1 (n_86), .B2 (n_5),
       .C1 (n_99), .C2 (n_22), .ZN (n_153));
  oai222d1 g3777__3680(.A1 (n_115), .A2 (n_65), .B1 (n_86), .B2 (n_16),
       .C1 (n_99), .C2 (n_27), .ZN (n_152));
  oai222d1 g3778__1617(.A1 (n_110), .A2 (n_65), .B1 (n_86), .B2 (n_9),
       .C1 (n_99), .C2 (n_35), .ZN (n_151));
  oai222d1 g3779__2802(.A1 (n_108), .A2 (n_65), .B1 (n_86), .B2 (n_2),
       .C1 (n_99), .C2 (n_30), .ZN (n_150));
  oai222d1 g3780__1705(.A1 (n_109), .A2 (n_65), .B1 (n_86), .B2 (n_6),
       .C1 (n_99), .C2 (n_23), .ZN (n_149));
  oai222d1 g3781__5122(.A1 (n_103), .A2 (n_65), .B1 (n_86), .B2 (n_15),
       .C1 (n_99), .C2 (n_29), .ZN (n_148));
  oai222d1 g3782__8246(.A1 (n_106), .A2 (n_65), .B1 (n_86), .B2 (n_17),
       .C1 (n_99), .C2 (n_34), .ZN (n_147));
  oai222d1 g3783__7098(.A1 (n_105), .A2 (n_65), .B1 (n_86), .B2 (n_3),
       .C1 (n_99), .C2 (n_24), .ZN (n_146));
  oai222d1 g3784__6131(.A1 (n_104), .A2 (n_65), .B1 (n_86), .B2 (n_8),
       .C1 (n_99), .C2 (n_20), .ZN (n_145));
  oai222d1 g3785__1881(.A1 (n_107), .A2 (n_65), .B1 (n_86), .B2 (n_13),
       .C1 (n_99), .C2 (n_33), .ZN (n_144));
  oai222d1 g3786__5115(.A1 (n_102), .A2 (n_65), .B1 (n_86), .B2 (n_11),
       .C1 (n_99), .C2 (n_19), .ZN (n_143));
  oai222d1 g3787__7482(.A1 (n_101), .A2 (n_65), .B1 (n_86), .B2 (n_14),
       .C1 (n_99), .C2 (n_21), .ZN (n_142));
  oai222d1 g3788__4733(.A1 (n_114), .A2 (n_65), .B1 (n_86), .B2 (n_12),
       .C1 (n_99), .C2 (n_32), .ZN (n_141));
  ah01d1 g3789__6161(.A (n_97), .B (i_cur[1]), .CO (n_139), .S (n_140));
  aor222d1 g3790__9315(.A1 (n_96), .A2 (plain_text[8]), .B1 (n_88), .B2
       (x_cur[8]), .C1 (n_85), .C2 (y_cur[8]), .Z (n_138));
  aor222d1 g3791__9945(.A1 (n_96), .A2 (plain_text[0]), .B1 (n_88), .B2
       (x_cur[0]), .C1 (n_85), .C2 (y_cur[0]), .Z (n_137));
  aor222d1 g3792__2883(.A1 (n_96), .A2 (plain_text[4]), .B1 (n_88), .B2
       (x_cur[4]), .C1 (n_85), .C2 (y_cur[4]), .Z (n_136));
  aor222d1 g3793__2346(.A1 (n_96), .A2 (plain_text[6]), .B1 (n_88), .B2
       (x_cur[6]), .C1 (n_85), .C2 (y_cur[6]), .Z (n_135));
  aor222d1 g3794__1666(.A1 (n_96), .A2 (plain_text[12]), .B1 (n_88),
       .B2 (x_cur[12]), .C1 (n_85), .C2 (y_cur[12]), .Z (n_134));
  aor222d1 g3795__7410(.A1 (n_96), .A2 (plain_text[9]), .B1 (n_88), .B2
       (x_cur[9]), .C1 (n_85), .C2 (y_cur[9]), .Z (n_133));
  aor222d1 g3796__6417(.A1 (n_96), .A2 (plain_text[10]), .B1 (n_88),
       .B2 (x_cur[10]), .C1 (n_85), .C2 (y_cur[10]), .Z (n_132));
  oai21d1 g3798__5477(.A (n_121), .B1 (n_87), .B2 (n_9), .ZN (n_131));
  aor222d1 g3799__2398(.A1 (n_96), .A2 (plain_text[14]), .B1 (n_88),
       .B2 (x_cur[14]), .C1 (n_85), .C2 (y_cur[14]), .Z (n_130));
  aor222d1 g3800__5107(.A1 (n_96), .A2 (plain_text[15]), .B1 (n_88),
       .B2 (x_cur[15]), .C1 (n_85), .C2 (y_cur[15]), .Z (n_129));
  oai21d1 g3801__6260(.A (n_120), .B1 (n_87), .B2 (n_16), .ZN (n_128));
  oai21d1 g3802__4319(.A (n_117), .B1 (n_87), .B2 (n_2), .ZN (n_127));
  oai21d1 g3803__8428(.A (n_118), .B1 (n_87), .B2 (n_3), .ZN (n_126));
  oai21d1 g3804__5526(.A (n_119), .B1 (n_87), .B2 (n_11), .ZN (n_125));
  oai21d1 g3805__6783(.A (n_116), .B1 (n_87), .B2 (n_1), .ZN (n_124));
  aor222d1 g3806__3680(.A1 (n_96), .A2 (plain_text[13]), .B1 (n_88),
       .B2 (x_cur[13]), .C1 (n_85), .C2 (y_cur[13]), .Z (n_123));
  aor21d1 g3807__1617(.A (reset), .B1 (n_98), .B2 (n_47), .Z (n_122));
  aoi22d1 g3808__2802(.A1 (n_96), .A2 (plain_text[11]), .B1 (n_85), .B2
       (y_cur[11]), .ZN (n_121));
  aoi22d1 g3809__1705(.A1 (n_96), .A2 (plain_text[1]), .B1 (n_85), .B2
       (y_cur[1]), .ZN (n_120));
  aoi22d1 g3810__5122(.A1 (n_96), .A2 (plain_text[5]), .B1 (n_85), .B2
       (y_cur[5]), .ZN (n_119));
  aoi22d1 g3811__8246(.A1 (n_96), .A2 (plain_text[3]), .B1 (n_85), .B2
       (y_cur[3]), .ZN (n_118));
  aoi22d1 g3812__7098(.A1 (n_96), .A2 (plain_text[2]), .B1 (n_85), .B2
       (y_cur[2]), .ZN (n_117));
  aoi22d1 g3813__6131(.A1 (n_96), .A2 (plain_text[7]), .B1 (n_85), .B2
       (y_cur[7]), .ZN (n_116));
  aoim22d1 g3814__1881(.A1 (n_63), .A2 (n_82), .B1 (n_63), .B2 (n_82),
       .Z (n_115));
  aoim22d1 g3815__5115(.A1 (n_64), .A2 (n_91), .B1 (n_64), .B2 (n_91),
       .Z (n_114));
  aoim22d1 g3816__7482(.A1 (n_68), .A2 (n_90), .B1 (n_68), .B2 (n_90),
       .Z (n_113));
  aoim22d1 g3817__4733(.A1 (n_66), .A2 (n_89), .B1 (n_66), .B2 (n_89),
       .Z (n_112));
  aoim22d1 g3818__6161(.A1 (n_69), .A2 (n_92), .B1 (n_69), .B2 (n_92),
       .Z (n_111));
  aoim22d1 g3819__9315(.A1 (n_73), .A2 (n_95), .B1 (n_73), .B2 (n_95),
       .Z (n_110));
  aoim22d1 g3820__9945(.A1 (n_62), .A2 (n_83), .B1 (n_62), .B2 (n_83),
       .Z (n_109));
  aoim22d1 g3821__2883(.A1 (n_59), .A2 (n_81), .B1 (n_59), .B2 (n_81),
       .Z (n_108));
  aoim22d1 g3822__2346(.A1 (n_55), .A2 (n_76), .B1 (n_55), .B2 (n_76),
       .Z (n_107));
  aoim22d1 g3823__1666(.A1 (n_58), .A2 (n_79), .B1 (n_58), .B2 (n_79),
       .Z (n_106));
  aoim22d1 g3824__7410(.A1 (n_57), .A2 (n_77), .B1 (n_57), .B2 (n_77),
       .Z (n_105));
  aoim22d1 g3825__6417(.A1 (n_56), .A2 (n_78), .B1 (n_56), .B2 (n_78),
       .Z (n_104));
  aoim22d1 g3826__5477(.A1 (n_60), .A2 (n_80), .B1 (n_60), .B2 (n_80),
       .Z (n_103));
  aoim22d1 g3827__2398(.A1 (n_61), .A2 (n_75), .B1 (n_61), .B2 (n_75),
       .Z (n_102));
  aoim22d1 g3828__5107(.A1 (n_67), .A2 (n_74), .B1 (n_67), .B2 (n_74),
       .Z (n_101));
  aoim22d1 g3829__6260(.A1 (n_70), .A2 (n_93), .B1 (n_70), .B2 (n_93),
       .Z (n_100));
  ah01d1 g3830__4319(.A (n_45), .B (i_cur[0]), .CO (n_97), .S (n_98));
  ora21d1 g3831__8428(.A (n_94), .B1 (n_255), .B2 (n_47), .Z (n_99));
  nd12d1 g3832__5526(.A1 (n_84), .A2 (n_94), .ZN (n_96));
  inv0d1 g3833(.I (n_88), .ZN (n_87));
  inv0d1 g3834(.I (n_86), .ZN (n_85));
  nr02d1 g3835__6783(.A1 (n_255), .A2 (n_72), .ZN (n_84));
  aoim22d1 g3836__3680(.A1 (n_37), .A2 (y_cur[11]), .B1 (n_37), .B2
       (y_cur[11]), .Z (n_95));
  nd02d1 g3837__1617(.A1 (n_71), .A2 (n_255), .ZN (n_94));
  aoim22d1 g3838__2802(.A1 (n_48), .A2 (y_cur[7]), .B1 (n_48), .B2
       (y_cur[7]), .Z (n_93));
  aoim22d1 g3839__1705(.A1 (n_53), .A2 (y_cur[8]), .B1 (n_53), .B2
       (y_cur[8]), .Z (n_92));
  aoim22d1 g3840__5122(.A1 (n_51), .A2 (y_cur[0]), .B1 (n_51), .B2
       (y_cur[0]), .Z (n_91));
  aoim22d1 g3841__8246(.A1 (n_36), .A2 (y_cur[9]), .B1 (n_36), .B2
       (y_cur[9]), .Z (n_90));
  aoim22d1 g3842__7098(.A1 (n_49), .A2 (y_cur[10]), .B1 (n_49), .B2
       (y_cur[10]), .Z (n_89));
  an02d1 g3843__6131(.A1 (n_72), .A2 (n_28), .Z (n_88));
  or02d1 g3844__1881(.A1 (n_71), .A2 (n_28), .Z (n_86));
  aoim22d1 g3845__5115(.A1 (n_54), .A2 (y_cur[12]), .B1 (n_54), .B2
       (y_cur[12]), .Z (n_83));
  aoim22d1 g3846__7482(.A1 (n_39), .A2 (y_cur[1]), .B1 (n_39), .B2
       (y_cur[1]), .Z (n_82));
  aoim22d1 g3847__4733(.A1 (n_38), .A2 (y_cur[2]), .B1 (n_38), .B2
       (y_cur[2]), .Z (n_81));
  aoim22d1 g3848__6161(.A1 (n_41), .A2 (y_cur[13]), .B1 (n_41), .B2
       (y_cur[13]), .Z (n_80));
  aoim22d1 g3849__9315(.A1 (n_42), .A2 (y_cur[14]), .B1 (n_42), .B2
       (y_cur[14]), .Z (n_79));
  aoim22d1 g3850__9945(.A1 (n_52), .A2 (y_cur[15]), .B1 (n_52), .B2
       (y_cur[15]), .Z (n_78));
  aoim22d1 g3851__2883(.A1 (n_43), .A2 (y_cur[3]), .B1 (n_43), .B2
       (y_cur[3]), .Z (n_77));
  aoim22d1 g3852__2346(.A1 (n_50), .A2 (y_cur[4]), .B1 (n_50), .B2
       (y_cur[4]), .Z (n_76));
  aoim22d1 g3853__1666(.A1 (n_40), .A2 (y_cur[5]), .B1 (n_40), .B2
       (y_cur[5]), .Z (n_75));
  aoim22d1 g3854__7410(.A1 (n_44), .A2 (y_cur[6]), .B1 (n_44), .B2
       (y_cur[6]), .Z (n_74));
  mx02d1 g3855__6417(.I0 (x_cur[9]), .I1 (n_7), .S (round_key[11]), .Z
       (n_73));
  aoi21d1 g3856__5477(.A (reset), .B1 (n_170), .B2 (start), .ZN (n_72));
  oai21d1 g3857__2398(.A (n_10), .B1 (n_18), .B2 (n_169), .ZN (n_71));
  mx02d1 g3858__5107(.I0 (x_cur[5]), .I1 (n_11), .S (round_key[7]), .Z
       (n_70));
  mx02d1 g3859__6260(.I0 (x_cur[6]), .I1 (n_14), .S (round_key[8]), .Z
       (n_69));
  mx02d1 g3860__4319(.I0 (x_cur[7]), .I1 (n_1), .S (round_key[9]), .Z
       (n_68));
  mx02d1 g3861__8428(.I0 (x_cur[4]), .I1 (n_13), .S (round_key[6]), .Z
       (n_67));
  mx02d1 g3862__5526(.I0 (x_cur[8]), .I1 (n_4), .S (round_key[10]), .Z
       (n_66));
  or02d1 g3863__6783(.A1 (n_255), .A2 (n_46), .Z (n_65));
  mx02d1 g3864__3680(.I0 (x_cur[14]), .I1 (n_17), .S (round_key[0]), .Z
       (n_64));
  mx02d1 g3865__1617(.I0 (x_cur[15]), .I1 (n_8), .S (round_key[1]), .Z
       (n_63));
  mx02d1 g3866__2802(.I0 (x_cur[10]), .I1 (n_5), .S (round_key[12]), .Z
       (n_62));
  mx02d1 g3867__1705(.I0 (x_cur[3]), .I1 (n_3), .S (round_key[5]), .Z
       (n_61));
  mx02d1 g3868__5122(.I0 (x_cur[11]), .I1 (n_9), .S (round_key[13]), .Z
       (n_60));
  mx02d1 g3869__8246(.I0 (x_cur[0]), .I1 (n_12), .S (round_key[2]), .Z
       (n_59));
  mx02d1 g3870__7098(.I0 (x_cur[12]), .I1 (n_6), .S (round_key[14]), .Z
       (n_58));
  mx02d1 g3871__6131(.I0 (x_cur[1]), .I1 (n_16), .S (round_key[3]), .Z
       (n_57));
  mx02d1 g3872__1881(.I0 (x_cur[13]), .I1 (n_15), .S (round_key[15]),
       .Z (n_56));
  mx02d1 g3873__5115(.I0 (x_cur[2]), .I1 (n_2), .S (round_key[4]), .Z
       (n_55));
  inv0d0 g3874(.I (n_47), .ZN (n_46));
  nd02d1 g3875__7482(.A1 (x_cur[11]), .A2 (x_cur[4]), .ZN (n_54));
  nd02d1 g3876__4733(.A1 (x_cur[7]), .A2 (x_cur[0]), .ZN (n_53));
  nd02d1 g3877__6161(.A1 (x_cur[14]), .A2 (x_cur[7]), .ZN (n_52));
  nd02d1 g3878__9315(.A1 (x_cur[15]), .A2 (x_cur[8]), .ZN (n_51));
  nd02d1 g3879__9945(.A1 (x_cur[12]), .A2 (x_cur[3]), .ZN (n_50));
  nd02d1 g3880__2883(.A1 (x_cur[9]), .A2 (x_cur[2]), .ZN (n_49));
  nd02d1 g3881__2346(.A1 (x_cur[15]), .A2 (x_cur[6]), .ZN (n_48));
  nd02d1 g3882__1666(.A1 (n_170), .A2 (n_255), .ZN (n_45));
  nr02d1 g3883__7410(.A1 (start), .A2 (reset), .ZN (n_47));
  nd02d1 g3884__6417(.A1 (x_cur[14]), .A2 (x_cur[5]), .ZN (n_44));
  nd02d1 g3885__5477(.A1 (x_cur[11]), .A2 (x_cur[2]), .ZN (n_43));
  nd02d1 g3886__2398(.A1 (x_cur[13]), .A2 (x_cur[6]), .ZN (n_42));
  nd02d1 g3887__5107(.A1 (x_cur[12]), .A2 (x_cur[5]), .ZN (n_41));
  nd02d1 g3888__6260(.A1 (x_cur[13]), .A2 (x_cur[4]), .ZN (n_40));
  nd02d1 g3889__4319(.A1 (x_cur[9]), .A2 (x_cur[0]), .ZN (n_39));
  nd02d1 g3890__8428(.A1 (x_cur[10]), .A2 (x_cur[1]), .ZN (n_38));
  nd02d1 g3891__5526(.A1 (x_cur[10]), .A2 (x_cur[3]), .ZN (n_37));
  nd02d1 g3892__6783(.A1 (x_cur[8]), .A2 (x_cur[1]), .ZN (n_36));
  inv0d0 g3893(.I (plain_text[27]), .ZN (n_35));
  inv0d0 g3894(.I (plain_text[30]), .ZN (n_34));
  inv0d0 g3895(.I (plain_text[20]), .ZN (n_33));
  inv0d0 g3896(.I (plain_text[16]), .ZN (n_32));
  inv0d0 g3897(.I (plain_text[24]), .ZN (n_31));
  inv0d0 g3898(.I (plain_text[18]), .ZN (n_30));
  inv0d0 g3899(.I (plain_text[29]), .ZN (n_29));
  inv0d0 g3944(.I (n_255), .ZN (n_28));
  inv0d0 g3945(.I (plain_text[17]), .ZN (n_27));
  inv0d0 g3946(.I (plain_text[23]), .ZN (n_26));
  inv0d0 g3947(.I (plain_text[25]), .ZN (n_25));
  inv0d0 g3948(.I (plain_text[19]), .ZN (n_24));
  inv0d0 g3949(.I (plain_text[28]), .ZN (n_23));
  inv0d0 g3950(.I (plain_text[26]), .ZN (n_22));
  inv0d0 g3951(.I (plain_text[22]), .ZN (n_21));
  inv0d0 g3952(.I (plain_text[31]), .ZN (n_20));
  inv0d0 g3953(.I (plain_text[21]), .ZN (n_19));
  dfnrb1 \i_cur_reg[0] (.CP (clk), .D (n_122), .Q (i_cur[0]), .QN
       (n_18));
  dfnrb1 \x_cur_reg[0] (.CP (clk), .D (n_141), .Q (x_cur[0]), .QN
       (n_12));
  dfnrb1 \x_cur_reg[1] (.CP (clk), .D (n_152), .Q (x_cur[1]), .QN
       (n_16));
  dfnrb1 \x_cur_reg[2] (.CP (clk), .D (n_150), .Q (x_cur[2]), .QN
       (n_2));
  dfnrb1 \x_cur_reg[3] (.CP (clk), .D (n_146), .Q (x_cur[3]), .QN
       (n_3));
  dfnrb1 \x_cur_reg[4] (.CP (clk), .D (n_144), .Q (x_cur[4]), .QN
       (n_13));
  dfnrb1 \x_cur_reg[5] (.CP (clk), .D (n_143), .Q (x_cur[5]), .QN
       (n_11));
  dfnrb1 \x_cur_reg[6] (.CP (clk), .D (n_142), .Q (x_cur[6]), .QN
       (n_14));
  dfnrb1 \x_cur_reg[7] (.CP (clk), .D (n_156), .Q (x_cur[7]), .QN
       (n_1));
  dfnrb1 \x_cur_reg[8] (.CP (clk), .D (n_155), .Q (x_cur[8]), .QN
       (n_4));
  dfnrb1 \x_cur_reg[9] (.CP (clk), .D (n_154), .Q (x_cur[9]), .QN
       (n_7));
  dfnrb1 \x_cur_reg[10] (.CP (clk), .D (n_153), .Q (x_cur[10]), .QN
       (n_5));
  dfnrb1 \x_cur_reg[11] (.CP (clk), .D (n_151), .Q (x_cur[11]), .QN
       (n_9));
  dfnrb1 \x_cur_reg[12] (.CP (clk), .D (n_149), .Q (x_cur[12]), .QN
       (n_6));
  dfnrb1 \x_cur_reg[13] (.CP (clk), .D (n_148), .Q (x_cur[13]), .QN
       (n_15));
  dfnrb1 \x_cur_reg[14] (.CP (clk), .D (n_147), .Q (x_cur[14]), .QN
       (n_17));
  dfnrb1 \x_cur_reg[15] (.CP (clk), .D (n_145), .Q (x_cur[15]), .QN
       (n_8));
  inv0d0 drc_bufs4004(.I (reset), .ZN (n_10));
  dfnrq4 \i_cur_reg[5] (.CP (clk), .D (n_167), .Q (n_255));
endmodule

module key_gen(clk, reset, start, key, round_key, done);
  input clk, reset, start;
  input [63:0] key;
  output [15:0] round_key;
  output done;
  wire clk, reset, start;
  wire [63:0] key;
  wire [15:0] round_key;
  wire done;
  wire [15:0] key1;
  wire [15:0] key2;
  wire [15:0] key0;
  wire [5:0] i_cur;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_95, n_96, n_97, n_98;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_242;
  xr02d1 g3040__3680(.A1 (round_key[4]), .A2 (key1[1]), .Z (n_172));
  dfnrq1 \key1_reg[1] (.CP (clk), .D (n_168), .Q (key1[1]));
  oai22d1 g3042__1617(.A1 (n_174), .A2 (key2[1]), .B1 (n_171), .B2
       (n_151), .ZN (n_168));
  dfnrn1 \key2_reg[1] (.CP (clk), .D (n_166), .QN (key2[1]));
  dfnrq1 \key0_reg[14] (.CP (clk), .D (n_157), .Q (key0[14]));
  dfnrq1 \key0_reg[15] (.CP (clk), .D (n_156), .Q (key0[15]));
  dfnrq1 \key0_reg[0] (.CP (clk), .D (n_161), .Q (key0[0]));
  dfnrq1 \key0_reg[5] (.CP (clk), .D (n_167), .Q (key0[5]));
  dfnrq1 \key0_reg[6] (.CP (clk), .D (n_165), .Q (key0[6]));
  dfnrq1 \key0_reg[13] (.CP (clk), .D (n_158), .Q (key0[13]));
  or03d1 g3050__2802(.A1 (n_174), .A2 (n_154), .A3 (i_cur[5]), .Z
       (n_170));
  dfnrq1 \key0_reg[8] (.CP (clk), .D (n_163), .Q (key0[8]));
  dfnrq1 \key0_reg[9] (.CP (clk), .D (n_162), .Q (key0[9]));
  dfnrq1 \key0_reg[10] (.CP (clk), .D (n_155), .Q (key0[10]));
  dfnrq1 \key0_reg[11] (.CP (clk), .D (n_160), .Q (key0[11]));
  dfnrq1 \key0_reg[12] (.CP (clk), .D (n_159), .Q (key0[12]));
  dfnrq1 \key0_reg[7] (.CP (clk), .D (n_164), .Q (key0[7]));
  aor22d1 g3057__1705(.A1 (n_152), .A2 (key1[5]), .B1 (n_153), .B2
       (key[5]), .Z (n_167));
  aor22d1 g3058__5122(.A1 (n_152), .A2 (round_key[1]), .B1 (n_153), .B2
       (key[33]), .Z (n_166));
  aor22d1 g3059__8246(.A1 (n_152), .A2 (key1[6]), .B1 (n_153), .B2
       (key[6]), .Z (n_165));
  aor22d1 g3060__7098(.A1 (n_152), .A2 (key1[7]), .B1 (n_153), .B2
       (key[7]), .Z (n_164));
  aor22d1 g3061__6131(.A1 (n_152), .A2 (key1[8]), .B1 (n_153), .B2
       (key[8]), .Z (n_163));
  aor22d1 g3062__1881(.A1 (n_152), .A2 (key1[9]), .B1 (n_153), .B2
       (key[9]), .Z (n_162));
  aor22d1 g3063__5115(.A1 (n_152), .A2 (key1[0]), .B1 (n_153), .B2
       (key[0]), .Z (n_161));
  aor22d1 g3064__7482(.A1 (n_152), .A2 (key1[11]), .B1 (n_153), .B2
       (key[11]), .Z (n_160));
  aor22d1 g3065__4733(.A1 (n_152), .A2 (key1[12]), .B1 (n_153), .B2
       (key[12]), .Z (n_159));
  aor22d1 g3066__6161(.A1 (n_152), .A2 (key1[13]), .B1 (n_153), .B2
       (key[13]), .Z (n_158));
  aor22d1 g3067__9315(.A1 (n_152), .A2 (key1[14]), .B1 (n_153), .B2
       (key[14]), .Z (n_157));
  aor22d1 g3068__9945(.A1 (n_152), .A2 (key1[15]), .B1 (n_153), .B2
       (key[15]), .Z (n_156));
  aor22d1 g3069__2883(.A1 (n_152), .A2 (key1[10]), .B1 (n_153), .B2
       (key[10]), .Z (n_155));
  inv0d0 g3070(.I (n_154), .ZN (n_169));
  nr03d1 g3071__2346(.A1 (i_cur[3]), .A2 (i_cur[2]), .A3 (i_cur[4]),
       .ZN (n_154));
  xr02d1 g3072__1666(.A1 (round_key[8]), .A2 (key1[5]), .Z (n_173));
  inv0d1 g3073(.I (n_171), .ZN (n_153));
  nd12d2 g3074__7410(.A1 (reset), .A2 (start), .ZN (n_171));
  inv0d1 g3075(.I (n_152), .ZN (n_174));
  nr02d2 g3076__6417(.A1 (start), .A2 (reset), .ZN (n_152));
  inv0d0 g3077(.I (key[17]), .ZN (n_151));
  dfnrq1 \i_cur_reg[0] (.CP (clk), .D (n_138), .Q (i_cur[0]));
  dfnrq1 \i_cur_reg[1] (.CP (clk), .D (n_137), .Q (i_cur[1]));
  dfnrq1 \i_cur_reg[3] (.CP (clk), .D (n_144), .Q (i_cur[3]));
  dfnrq1 \i_cur_reg[4] (.CP (clk), .D (n_147), .Q (i_cur[4]));
  dfnrq1 \i_cur_reg[5] (.CP (clk), .D (n_148), .Q (i_cur[5]));
  dfnrq1 \key1_reg[0] (.CP (clk), .D (n_105), .Q (key1[0]));
  dfnrq1 \key1_reg[3] (.CP (clk), .D (n_106), .Q (key1[3]));
  dfnrq1 \key1_reg[4] (.CP (clk), .D (n_115), .Q (key1[4]));
  dfnrq1 \key1_reg[5] (.CP (clk), .D (n_122), .Q (key1[5]));
  dfnrq1 \key1_reg[6] (.CP (clk), .D (n_121), .Q (key1[6]));
  dfnrq1 \key1_reg[7] (.CP (clk), .D (n_120), .Q (key1[7]));
  dfnrq1 \key1_reg[8] (.CP (clk), .D (n_119), .Q (key1[8]));
  dfnrq1 \key1_reg[9] (.CP (clk), .D (n_118), .Q (key1[9]));
  dfnrq1 \key1_reg[10] (.CP (clk), .D (n_117), .Q (key1[10]));
  dfnrq1 \key1_reg[11] (.CP (clk), .D (n_116), .Q (key1[11]));
  dfnrq1 \key1_reg[12] (.CP (clk), .D (n_123), .Q (key1[12]));
  dfnrq1 \key1_reg[13] (.CP (clk), .D (n_109), .Q (key1[13]));
  dfnrq1 \key1_reg[14] (.CP (clk), .D (n_108), .Q (key1[14]));
  dfnrq1 \key1_reg[15] (.CP (clk), .D (n_107), .Q (key1[15]));
  dfnrq1 \key3_reg[1] (.CP (clk), .D (n_141), .Q (round_key[1]));
  dfnrq1 \key3_reg[2] (.CP (clk), .D (n_140), .Q (round_key[2]));
  dfnrq1 \key3_reg[3] (.CP (clk), .D (n_139), .Q (round_key[3]));
  dfnrq1 \key3_reg[4] (.CP (clk), .D (n_134), .Q (round_key[4]));
  aoim21d1 g3423__5477(.A (n_174), .B1 (n_145), .B2 (i_cur[5]), .ZN
       (n_148));
  an02d1 g3424__2398(.A1 (n_95), .A2 (n_146), .Z (n_147));
  ah01d1 g3425__5107(.A (n_92), .B (i_cur[4]), .CO (n_145), .S (n_146));
  oan211d1 g3427__6260(.A (n_174), .B (n_142), .C1 (n_131), .C2
       (i_cur[3]), .ZN (n_144));
  oai22d1 g3432__4319(.A1 (n_174), .A2 (n_136), .B1 (n_95), .B2
       (reset), .ZN (n_143));
  nd02d1 g3433__8428(.A1 (n_131), .A2 (i_cur[3]), .ZN (n_142));
  oai22d1 g3436__5526(.A1 (n_170), .A2 (n_135), .B1 (n_171), .B2
       (n_101), .ZN (n_141));
  oai22d1 g3437__6783(.A1 (n_170), .A2 (n_133), .B1 (n_171), .B2
       (n_96), .ZN (n_140));
  oai22d1 g3438__3680(.A1 (n_170), .A2 (n_132), .B1 (n_171), .B2
       (n_102), .ZN (n_139));
  oai21d1 g3441__1617(.A (n_93), .B1 (start), .B2 (n_130), .ZN (n_138));
  oai21d1 g3442__2802(.A (n_93), .B1 (start), .B2 (n_124), .ZN (n_137));
  oai21d1 g3443__1705(.A (n_131), .B1 (n_91), .B2 (i_cur[2]), .ZN
       (n_136));
  aoim22d1 g3444__5122(.A1 (n_129), .A2 (n_172), .B1 (n_129), .B2
       (n_172), .Z (n_135));
  oai22d1 g3445__8246(.A1 (n_170), .A2 (n_126), .B1 (n_171), .B2
       (n_100), .ZN (n_134));
  aoim22d1 g3446__7098(.A1 (n_128), .A2 (n_111), .B1 (n_128), .B2
       (n_111), .Z (n_133));
  aoim22d1 g3447__6131(.A1 (n_127), .A2 (n_113), .B1 (n_127), .B2
       (n_113), .Z (n_132));
  nd02d1 g3448__1881(.A1 (n_91), .A2 (i_cur[2]), .ZN (n_131));
  aoim22d1 g3449__5115(.A1 (n_125), .A2 (i_cur[0]), .B1 (n_125), .B2
       (i_cur[0]), .Z (n_130));
  aoim22d1 g3450__7482(.A1 (n_112), .A2 (key0[1]), .B1 (n_112), .B2
       (key0[1]), .Z (n_129));
  aoim22d1 g3451__4733(.A1 (n_113), .A2 (key0[2]), .B1 (n_113), .B2
       (key0[2]), .Z (n_128));
  aoim22d1 g3452__6161(.A1 (n_114), .A2 (n_110), .B1 (n_114), .B2
       (n_110), .Z (n_126));
  aoim22d1 g3453__9315(.A1 (n_110), .A2 (key0[3]), .B1 (n_110), .B2
       (key0[3]), .Z (n_127));
  aoim22d1 g3462__9945(.A1 (n_103), .A2 (i_cur[1]), .B1 (n_103), .B2
       (i_cur[1]), .Z (n_124));
  ora31d1 g3468__2883(.A (i_cur[5]), .B1 (i_cur[1]), .B2 (i_cur[0]),
       .B3 (n_169), .Z (n_125));
  aor22d1 g3471__2346(.A1 (n_97), .A2 (key[28]), .B1 (n_95), .B2
       (key2[12]), .Z (n_123));
  aor22d1 g3472__1666(.A1 (n_97), .A2 (key[21]), .B1 (n_95), .B2
       (key2[5]), .Z (n_122));
  aor22d1 g3473__7410(.A1 (n_97), .A2 (key[22]), .B1 (n_95), .B2
       (key2[6]), .Z (n_121));
  aor22d1 g3474__6417(.A1 (n_97), .A2 (key[23]), .B1 (n_95), .B2
       (key2[7]), .Z (n_120));
  aor22d1 g3475__5477(.A1 (n_97), .A2 (key[24]), .B1 (n_95), .B2
       (key2[8]), .Z (n_119));
  aor22d1 g3476__2398(.A1 (n_97), .A2 (key[25]), .B1 (n_95), .B2
       (key2[9]), .Z (n_118));
  aor22d1 g3477__5107(.A1 (n_97), .A2 (key[26]), .B1 (n_95), .B2
       (key2[10]), .Z (n_117));
  aor22d1 g3478__6260(.A1 (n_97), .A2 (key[27]), .B1 (n_95), .B2
       (key2[11]), .Z (n_116));
  aor22d1 g3479__4319(.A1 (n_97), .A2 (key[20]), .B1 (n_95), .B2
       (key2[4]), .Z (n_115));
  inv0d0 g3481(.I (n_112), .ZN (n_111));
  aor22d1 g3482__8428(.A1 (n_97), .A2 (key[29]), .B1 (n_95), .B2
       (key2[13]), .Z (n_109));
  aor22d1 g3483__5526(.A1 (n_97), .A2 (key[30]), .B1 (n_95), .B2
       (key2[14]), .Z (n_108));
  aor22d1 g3484__6783(.A1 (n_97), .A2 (key[31]), .B1 (n_95), .B2
       (key2[15]), .Z (n_107));
  aor22d1 g3485__3680(.A1 (n_97), .A2 (key[19]), .B1 (n_95), .B2
       (key2[3]), .Z (n_106));
  aor22d1 g3486__1617(.A1 (n_97), .A2 (key[16]), .B1 (n_95), .B2
       (key2[0]), .Z (n_105));
  aor22d1 g3487__2802(.A1 (n_97), .A2 (key[18]), .B1 (n_95), .B2
       (key2[2]), .Z (n_104));
  aoim22d1 g3488__1705(.A1 (n_173), .A2 (key0[4]), .B1 (n_173), .B2
       (key0[4]), .Z (n_114));
  xr02d1 g3489__5122(.A1 (key1[3]), .A2 (round_key[6]), .Z (n_113));
  aoim22d1 g3490__8246(.A1 (n_98), .A2 (round_key[5]), .B1 (n_98), .B2
       (round_key[5]), .Z (n_112));
  xr02d1 g3491__7098(.A1 (key1[4]), .A2 (round_key[7]), .Z (n_110));
  nd12d1 g3492__6131(.A1 (i_cur[5]), .A2 (i_cur[0]), .ZN (n_103));
  inv0d0 g3493(.I (key[51]), .ZN (n_102));
  inv0d0 g3494(.I (key[49]), .ZN (n_101));
  inv0d0 g3495(.I (key[52]), .ZN (n_100));
  inv0d1 g3501(.I (n_171), .ZN (n_97));
  inv0d0 g3502(.I (key[50]), .ZN (n_96));
  inv0d1 g3514(.I (n_174), .ZN (n_95));
  inv0d0 drc_bufs3516(.I (reset), .ZN (n_93));
  an12d1 g2__1881(.A1 (n_131), .A2 (i_cur[3]), .Z (n_92));
  an12d1 g3520__5115(.A1 (n_103), .A2 (i_cur[1]), .Z (n_91));
  dfnrq1 \key0_reg[1] (.CP (clk), .D (n_35), .Q (key0[1]));
  dfnrq1 \key0_reg[2] (.CP (clk), .D (n_37), .Q (key0[2]));
  dfnrq1 \key0_reg[3] (.CP (clk), .D (n_34), .Q (key0[3]));
  dfnrq1 \key0_reg[4] (.CP (clk), .D (n_19), .Q (key0[4]));
  dfnrq1 \key2_reg[0] (.CP (clk), .D (n_21), .Q (key2[0]));
  dfnrq1 \key2_reg[2] (.CP (clk), .D (n_22), .Q (key2[2]));
  dfnrq1 \key2_reg[3] (.CP (clk), .D (n_46), .Q (key2[3]));
  dfnrq1 \key2_reg[4] (.CP (clk), .D (n_41), .Q (key2[4]));
  dfnrq1 \key2_reg[5] (.CP (clk), .D (n_47), .Q (key2[5]));
  dfnrq1 \key2_reg[6] (.CP (clk), .D (n_45), .Q (key2[6]));
  dfnrq1 \key2_reg[7] (.CP (clk), .D (n_44), .Q (key2[7]));
  dfnrq1 \key2_reg[8] (.CP (clk), .D (n_43), .Q (key2[8]));
  dfnrq1 \key2_reg[9] (.CP (clk), .D (n_42), .Q (key2[9]));
  dfnrq1 \key2_reg[10] (.CP (clk), .D (n_48), .Q (key2[10]));
  dfnrq1 \key2_reg[11] (.CP (clk), .D (n_20), .Q (key2[11]));
  dfnrq1 \key2_reg[12] (.CP (clk), .D (n_40), .Q (key2[12]));
  dfnrq1 \key2_reg[13] (.CP (clk), .D (n_39), .Q (key2[13]));
  dfnrq1 \key2_reg[14] (.CP (clk), .D (n_36), .Q (key2[14]));
  dfnrq1 \key2_reg[15] (.CP (clk), .D (n_38), .Q (key2[15]));
  dfnrq1 \key3_reg[0] (.CP (clk), .D (n_90), .Q (round_key[0]));
  dfnrq1 \key3_reg[5] (.CP (clk), .D (n_84), .Q (round_key[5]));
  dfnrq1 \key3_reg[6] (.CP (clk), .D (n_78), .Q (round_key[6]));
  dfnrq1 \key3_reg[7] (.CP (clk), .D (n_77), .Q (round_key[7]));
  dfnrq1 \key3_reg[8] (.CP (clk), .D (n_76), .Q (round_key[8]));
  dfnrq1 \key3_reg[9] (.CP (clk), .D (n_85), .Q (round_key[9]));
  dfnrq1 \key3_reg[10] (.CP (clk), .D (n_86), .Q (round_key[10]));
  dfnrq1 \key3_reg[11] (.CP (clk), .D (n_83), .Q (round_key[11]));
  dfnrq1 \key3_reg[12] (.CP (clk), .D (n_82), .Q (round_key[12]));
  dfnrq1 \key3_reg[13] (.CP (clk), .D (n_81), .Q (round_key[13]));
  dfnrq1 \key3_reg[14] (.CP (clk), .D (n_80), .Q (round_key[14]));
  dfnrq1 \key3_reg[15] (.CP (clk), .D (n_79), .Q (round_key[15]));
  oai22d1 g3954__7482(.A1 (n_89), .A2 (n_170), .B1 (n_171), .B2 (n_9),
       .ZN (n_90));
  aoim22d1 g3955__4733(.A1 (n_88), .A2 (n_26), .B1 (n_88), .B2 (n_26),
       .Z (n_89));
  aoim22d1 g3956__6161(.A1 (n_87), .A2 (n_172), .B1 (n_87), .B2
       (n_172), .Z (n_88));
  aoim22d1 g3966__9315(.A1 (n_75), .A2 (key0[0]), .B1 (n_75), .B2
       (key0[0]), .Z (n_87));
  oai22d1 g3969__9945(.A1 (n_170), .A2 (n_71), .B1 (n_171), .B2 (n_7),
       .ZN (n_86));
  oai22d1 g3970__2883(.A1 (n_170), .A2 (n_74), .B1 (n_171), .B2 (n_13),
       .ZN (n_85));
  oai22d1 g3971__2346(.A1 (n_170), .A2 (n_72), .B1 (n_171), .B2 (n_15),
       .ZN (n_84));
  oai22d1 g3972__1666(.A1 (n_170), .A2 (n_70), .B1 (n_171), .B2 (n_10),
       .ZN (n_83));
  oai22d1 g3973__7410(.A1 (n_170), .A2 (n_69), .B1 (n_171), .B2 (n_6),
       .ZN (n_82));
  oai22d1 g3974__6417(.A1 (n_170), .A2 (n_68), .B1 (n_171), .B2 (n_12),
       .ZN (n_81));
  oai22d1 g3975__5477(.A1 (n_170), .A2 (n_67), .B1 (n_171), .B2 (n_14),
       .ZN (n_80));
  oai22d1 g3976__2398(.A1 (n_170), .A2 (n_66), .B1 (n_171), .B2 (n_11),
       .ZN (n_79));
  oai22d1 g3977__5107(.A1 (n_170), .A2 (n_65), .B1 (n_171), .B2 (n_4),
       .ZN (n_78));
  oai22d1 g3978__6260(.A1 (n_170), .A2 (n_64), .B1 (n_171), .B2 (n_5),
       .ZN (n_77));
  oai22d1 g3979__4319(.A1 (n_170), .A2 (n_73), .B1 (n_171), .B2 (n_3),
       .ZN (n_76));
  aoim22d1 g3980__8428(.A1 (n_63), .A2 (i_cur[4]), .B1 (n_242), .B2
       (i_cur[4]), .Z (n_75));
  aoim22d1 g3981__5526(.A1 (n_61), .A2 (n_33), .B1 (n_61), .B2 (n_33),
       .Z (n_74));
  aoim22d1 g3982__6783(.A1 (n_60), .A2 (n_23), .B1 (n_60), .B2 (n_23),
       .Z (n_73));
  aoim22d1 g3983__3680(.A1 (n_54), .A2 (n_173), .B1 (n_54), .B2
       (n_173), .Z (n_72));
  aoim22d1 g3984__1617(.A1 (n_62), .A2 (n_31), .B1 (n_62), .B2 (n_31),
       .Z (n_71));
  aoim22d1 g3985__2802(.A1 (n_59), .A2 (n_30), .B1 (n_59), .B2 (n_30),
       .Z (n_70));
  aoim22d1 g3986__1705(.A1 (n_58), .A2 (n_32), .B1 (n_58), .B2 (n_32),
       .Z (n_69));
  aoim22d1 g3987__5122(.A1 (n_57), .A2 (n_29), .B1 (n_57), .B2 (n_29),
       .Z (n_68));
  aoim22d1 g3988__8246(.A1 (n_56), .A2 (n_28), .B1 (n_56), .B2 (n_28),
       .Z (n_67));
  aoim22d1 g3989__7098(.A1 (n_55), .A2 (n_27), .B1 (n_55), .B2 (n_27),
       .Z (n_66));
  aoim22d1 g3990__6131(.A1 (n_53), .A2 (n_25), .B1 (n_53), .B2 (n_25),
       .Z (n_65));
  aoim22d1 g3991__1881(.A1 (n_52), .A2 (n_24), .B1 (n_52), .B2 (n_24),
       .Z (n_64));
  aoim22d1 g3992__5115(.A1 (n_49), .A2 (i_cur[1]), .B1 (n_51), .B2
       (i_cur[1]), .Z (n_63));
  aoim22d1 g3993__7482(.A1 (n_30), .A2 (key0[10]), .B1 (n_30), .B2
       (key0[10]), .Z (n_62));
  aoim22d1 g3994__4733(.A1 (n_31), .A2 (key0[9]), .B1 (n_31), .B2
       (key0[9]), .Z (n_61));
  aoim22d1 g3995__6161(.A1 (n_33), .A2 (key0[8]), .B1 (n_33), .B2
       (key0[8]), .Z (n_60));
  aoim22d1 g3996__9315(.A1 (n_32), .A2 (key0[11]), .B1 (n_32), .B2
       (key0[11]), .Z (n_59));
  aoim22d1 g3997__9945(.A1 (n_29), .A2 (key0[12]), .B1 (n_29), .B2
       (key0[12]), .Z (n_58));
  aoim22d1 g3998__2883(.A1 (n_28), .A2 (key0[13]), .B1 (n_28), .B2
       (key0[13]), .Z (n_57));
  aoim22d1 g3999__2346(.A1 (n_27), .A2 (key0[14]), .B1 (n_27), .B2
       (key0[14]), .Z (n_56));
  aoim22d1 g4000__1666(.A1 (n_26), .A2 (key0[15]), .B1 (n_26), .B2
       (key0[15]), .Z (n_55));
  aoim22d1 g4001__7410(.A1 (n_25), .A2 (key0[5]), .B1 (n_25), .B2
       (key0[5]), .Z (n_54));
  aoim22d1 g4002__6417(.A1 (n_24), .A2 (key0[6]), .B1 (n_24), .B2
       (key0[6]), .Z (n_53));
  aoim22d1 g4003__5477(.A1 (n_23), .A2 (key0[7]), .B1 (n_23), .B2
       (key0[7]), .Z (n_52));
  aoi21d1 g4023__2398(.A (n_16), .B1 (n_18), .B2 (i_cur[3]), .ZN
       (n_51));
  oai22d1 g4025__6260(.A1 (n_16), .A2 (n_1), .B1 (i_cur[2]), .B2
       (i_cur[0]), .ZN (n_49));
  aor22d1 g4026__4319(.A1 (n_8), .A2 (round_key[10]), .B1 (n_0), .B2
       (key[42]), .Z (n_48));
  aor22d1 g4027__8428(.A1 (n_8), .A2 (round_key[5]), .B1 (n_0), .B2
       (key[37]), .Z (n_47));
  aor22d1 g4028__5526(.A1 (n_8), .A2 (round_key[3]), .B1 (n_0), .B2
       (key[35]), .Z (n_46));
  aor22d1 g4029__6783(.A1 (n_8), .A2 (round_key[6]), .B1 (n_0), .B2
       (key[38]), .Z (n_45));
  aor22d1 g4030__3680(.A1 (n_8), .A2 (round_key[7]), .B1 (n_0), .B2
       (key[39]), .Z (n_44));
  aor22d1 g4031__1617(.A1 (n_8), .A2 (round_key[8]), .B1 (n_0), .B2
       (key[40]), .Z (n_43));
  aor22d1 g4032__2802(.A1 (n_8), .A2 (round_key[9]), .B1 (n_0), .B2
       (key[41]), .Z (n_42));
  aor22d1 g4033__1705(.A1 (n_8), .A2 (round_key[4]), .B1 (n_0), .B2
       (key[36]), .Z (n_41));
  aor22d1 g4034__5122(.A1 (n_8), .A2 (round_key[12]), .B1 (n_0), .B2
       (key[44]), .Z (n_40));
  aor22d1 g4035__8246(.A1 (n_8), .A2 (round_key[13]), .B1 (n_0), .B2
       (key[45]), .Z (n_39));
  aor22d1 g4036__7098(.A1 (n_8), .A2 (round_key[15]), .B1 (n_0), .B2
       (key[47]), .Z (n_38));
  aor22d1 g4037__6131(.A1 (n_8), .A2 (key1[2]), .B1 (n_0), .B2
       (key[2]), .Z (n_37));
  aor22d1 g4038__1881(.A1 (n_8), .A2 (round_key[14]), .B1 (n_0), .B2
       (key[46]), .Z (n_36));
  aor22d1 g4039__5115(.A1 (n_8), .A2 (key1[1]), .B1 (n_0), .B2
       (key[1]), .Z (n_35));
  aor22d1 g4040__7482(.A1 (n_8), .A2 (key1[3]), .B1 (n_0), .B2
       (key[3]), .Z (n_34));
  aor22d1 g4041__4733(.A1 (n_8), .A2 (round_key[2]), .B1 (n_0), .B2
       (key[34]), .Z (n_22));
  aor22d1 g4042__6161(.A1 (n_8), .A2 (round_key[0]), .B1 (n_0), .B2
       (key[32]), .Z (n_21));
  aor22d1 g4043__9315(.A1 (n_8), .A2 (round_key[11]), .B1 (n_0), .B2
       (key[43]), .Z (n_20));
  aor22d1 g4044__9945(.A1 (n_8), .A2 (key1[4]), .B1 (n_0), .B2
       (key[4]), .Z (n_19));
  xr02d1 g4045__2883(.A1 (round_key[12]), .A2 (key1[9]), .Z (n_33));
  xr02d1 g4046__2346(.A1 (round_key[15]), .A2 (key1[12]), .Z (n_32));
  xr02d1 g4047__1666(.A1 (round_key[13]), .A2 (key1[10]), .Z (n_31));
  xr02d1 g4048__7410(.A1 (round_key[14]), .A2 (key1[11]), .Z (n_30));
  xr02d1 g4049__6417(.A1 (round_key[0]), .A2 (key1[13]), .Z (n_29));
  xr02d1 g4050__5477(.A1 (round_key[1]), .A2 (key1[14]), .Z (n_28));
  xr02d1 g4051__2398(.A1 (round_key[2]), .A2 (key1[15]), .Z (n_27));
  xr02d1 g4052__5107(.A1 (round_key[3]), .A2 (key1[0]), .Z (n_26));
  xr02d1 g4053__6260(.A1 (round_key[9]), .A2 (key1[6]), .Z (n_25));
  xr02d1 g4054__4319(.A1 (round_key[10]), .A2 (key1[7]), .Z (n_24));
  xr02d1 g4055__8428(.A1 (round_key[11]), .A2 (key1[8]), .Z (n_23));
  inv0d0 g4056(.I (n_17), .ZN (n_18));
  nr02d1 g4057__5526(.A1 (i_cur[1]), .A2 (n_1), .ZN (n_17));
  nr02d1 g4058__6783(.A1 (i_cur[0]), .A2 (i_cur[3]), .ZN (n_16));
  inv0d0 g4059(.I (key[53]), .ZN (n_15));
  inv0d0 g4060(.I (key[62]), .ZN (n_14));
  inv0d0 g4061(.I (key[57]), .ZN (n_13));
  inv0d0 g4062(.I (key[61]), .ZN (n_12));
  inv0d0 g4063(.I (key[63]), .ZN (n_11));
  inv0d0 g4064(.I (key[59]), .ZN (n_10));
  inv0d0 g4065(.I (key[48]), .ZN (n_9));
  inv0d2 g4070(.I (n_174), .ZN (n_8));
  inv0d0 g4071(.I (key[58]), .ZN (n_7));
  inv0d0 g4072(.I (key[60]), .ZN (n_6));
  inv0d0 g4073(.I (key[55]), .ZN (n_5));
  inv0d0 g4074(.I (key[54]), .ZN (n_4));
  inv0d0 g4075(.I (key[56]), .ZN (n_3));
  inv0d2 g4082(.I (n_171), .ZN (n_0));
  ora21d1 g2(.A (i_cur[3]), .B1 (n_17), .B2 (i_cur[0]), .Z (n_242));
  dfnrb1 \key1_reg[2] (.CP (clk), .D (n_104), .Q (key1[2]), .QN (n_98));
  dfnrb1 \i_cur_reg[2] (.CP (clk), .D (n_143), .Q (i_cur[2]), .QN
       (n_1));
endmodule

module simon_newer(clk, reset, start, key, plain_text, cipher_text,
     done);
  input clk, reset, start;
  input [63:0] key;
  input [31:0] plain_text;
  output [31:0] cipher_text;
  output done;
  wire clk, reset, start;
  wire [63:0] key;
  wire [31:0] plain_text;
  wire [31:0] cipher_text;
  wire done;
  wire [15:0] key_from_key;
  wire [2:0] j_cur;
  wire buffer, key_gen_start, keygen_done, n_2, n_3, n_4, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_14, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_226, n_227, n_704_BAR, start_prev;
  encrypt u_encrypt(.clk (clk), .reset (reset), .start (n_73),
       .round_key ({n_93, n_92, n_91, n_90, n_89, n_88, n_87, n_86,
       n_85, n_84, n_83, n_82, n_81, n_80, n_79, n_78}), .plain_text
       (plain_text), .cipher_text (cipher_text), .done (done));
  key_gen u_key_gen(.clk (clk), .reset (reset), .start (key_gen_start),
       .key (key), .round_key (key_from_key), .done (keygen_done));
  inv0d0 g1055(.I (n_77), .ZN (n_73));
  dfnrn1 buffer_reg(.CP (clk), .D (n_32), .QN (buffer));
  dfnrn1 start_prev_reg(.CP (clk), .D (n_40), .QN (start_prev));
  oai211d1 g2227__3680(.A (n_63), .B (n_43), .C1 (n_75), .C2 (n_23),
       .ZN (n_78));
  oai211d1 g2228__1617(.A (n_72), .B (n_57), .C1 (n_75), .C2 (n_22),
       .ZN (n_84));
  nd02d1 g2229__2802(.A1 (n_69), .A2 (n_70), .ZN (n_88));
  oaim211d1 g2230__1705(.A (n_62), .B (n_61), .C1 (n_704_BAR), .C2
       (key[46]), .ZN (n_92));
  oai211d1 g2231__5122(.A (n_58), .B (n_55), .C1 (n_39), .C2 (n_24),
       .ZN (n_89));
  an02d1 g2232__8246(.A1 (n_704_BAR), .A2 (n_77), .Z (key_gen_start));
  oai211d1 g2233__7098(.A (n_56), .B (n_54), .C1 (n_39), .C2 (n_28),
       .ZN (n_83));
  oai211d1 g2234__6131(.A (n_47), .B (n_46), .C1 (n_39), .C2 (n_21),
       .ZN (n_91));
  oai211d1 g2235__1881(.A (n_68), .B (n_52), .C1 (n_37), .C2 (n_25),
       .ZN (n_82));
  oai211d1 g2236__5115(.A (n_53), .B (n_44), .C1 (n_39), .C2 (n_20),
       .ZN (n_93));
  oai211d1 g2237__7482(.A (n_66), .B (n_51), .C1 (n_37), .C2 (n_17),
       .ZN (n_87));
  oai211d1 g2238__4733(.A (n_67), .B (n_48), .C1 (n_37), .C2 (n_30),
       .ZN (n_80));
  oai211d1 g2239__6161(.A (n_65), .B (n_45), .C1 (n_75), .C2 (n_18),
       .ZN (n_79));
  oai211d1 g2240__9315(.A (n_50), .B (n_49), .C1 (n_39), .C2 (n_19),
       .ZN (n_81));
  oai211d1 g2241__9945(.A (n_64), .B (n_41), .C1 (n_75), .C2 (n_31),
       .ZN (n_86));
  oai211d1 g2242__2883(.A (n_60), .B (n_42), .C1 (n_39), .C2 (n_29),
       .ZN (n_90));
  oai211d1 g2243__2346(.A (n_71), .B (n_59), .C1 (n_37), .C2 (n_27),
       .ZN (n_85));
  aoi22d1 g2244__1666(.A1 (n_38), .A2 (key_from_key[6]), .B1 (n_35),
       .B2 (key[6]), .ZN (n_72));
  aoi22d1 g2245__7410(.A1 (n_38), .A2 (key_from_key[7]), .B1 (n_35),
       .B2 (key[7]), .ZN (n_71));
  aoi222d1 g2246__6417(.A1 (key[10]), .A2 (n_35), .B1 (n_36), .B2
       (key[26]), .C1 (key[42]), .C2 (n_704_BAR), .ZN (n_70));
  aoi22d1 g2247__5477(.A1 (n_38), .A2 (key_from_key[10]), .B1 (n_34),
       .B2 (key[58]), .ZN (n_69));
  aoi22d1 g2248__2398(.A1 (n_38), .A2 (key_from_key[4]), .B1 (n_35),
       .B2 (key[4]), .ZN (n_68));
  nd02d1 g2249__5107(.A1 (start), .A2 (start_prev), .ZN (n_77));
  aoi22d1 g2250__6260(.A1 (n_38), .A2 (key_from_key[2]), .B1 (n_35),
       .B2 (key[2]), .ZN (n_67));
  aoi22d1 g2251__4319(.A1 (n_38), .A2 (key_from_key[9]), .B1 (n_35),
       .B2 (key[9]), .ZN (n_66));
  aoi22d1 g2252__8428(.A1 (n_38), .A2 (key_from_key[1]), .B1 (n_36),
       .B2 (key[17]), .ZN (n_65));
  aoi22d1 g2253__5526(.A1 (n_38), .A2 (key_from_key[8]), .B1 (n_35),
       .B2 (key[8]), .ZN (n_64));
  aoi22d1 g2254__6783(.A1 (n_38), .A2 (key_from_key[0]), .B1 (n_35),
       .B2 (key[0]), .ZN (n_63));
  aoi22d1 g2255__3680(.A1 (n_38), .A2 (key_from_key[14]), .B1 (n_36),
       .B2 (key[30]), .ZN (n_62));
  aoi22d1 g2256__1617(.A1 (n_34), .A2 (key[62]), .B1 (n_35), .B2
       (key[14]), .ZN (n_61));
  aoi22d1 g2257__2802(.A1 (n_35), .A2 (key[12]), .B1 (n_704_BAR), .B2
       (key[44]), .ZN (n_60));
  aoi22d1 g2258__1705(.A1 (n_34), .A2 (key[55]), .B1 (n_704_BAR), .B2
       (key[39]), .ZN (n_59));
  aoi22d1 g2259__5122(.A1 (n_35), .A2 (key[11]), .B1 (n_704_BAR), .B2
       (key[43]), .ZN (n_58));
  aoi22d1 g2260__8246(.A1 (n_36), .A2 (key[22]), .B1 (n_704_BAR), .B2
       (key[38]), .ZN (n_57));
  aoi22d1 g2262__7098(.A1 (n_35), .A2 (key[5]), .B1 (n_704_BAR), .B2
       (key[37]), .ZN (n_56));
  aoi22d1 g2263__6131(.A1 (n_34), .A2 (key[59]), .B1 (n_36), .B2
       (key[27]), .ZN (n_55));
  aoi22d1 g2264__1881(.A1 (n_34), .A2 (key[53]), .B1 (n_36), .B2
       (key[21]), .ZN (n_54));
  aoi22d1 g2265__5115(.A1 (n_35), .A2 (key[15]), .B1 (n_704_BAR), .B2
       (key[47]), .ZN (n_53));
  aoi22d1 g2266__7482(.A1 (n_34), .A2 (key[52]), .B1 (n_704_BAR), .B2
       (key[36]), .ZN (n_52));
  aoi22d1 g2267__4733(.A1 (n_34), .A2 (key[57]), .B1 (n_704_BAR), .B2
       (key[41]), .ZN (n_51));
  aoi22d1 g2268__6161(.A1 (n_34), .A2 (key[51]), .B1 (n_704_BAR), .B2
       (key[35]), .ZN (n_50));
  aoi22d1 g2269__9315(.A1 (n_36), .A2 (key[19]), .B1 (n_35), .B2
       (key[3]), .ZN (n_49));
  aoi22d1 g2270__9945(.A1 (n_34), .A2 (key[50]), .B1 (n_704_BAR), .B2
       (key[34]), .ZN (n_48));
  aoi22d1 g2271__2883(.A1 (n_35), .A2 (key[13]), .B1 (n_704_BAR), .B2
       (key[45]), .ZN (n_47));
  aoi22d1 g2272__2346(.A1 (n_34), .A2 (key[61]), .B1 (n_36), .B2
       (key[29]), .ZN (n_46));
  aoi22d1 g2273__1666(.A1 (n_35), .A2 (key[1]), .B1 (n_704_BAR), .B2
       (key[33]), .ZN (n_45));
  aoi22d1 g2274__7410(.A1 (n_34), .A2 (key[63]), .B1 (n_36), .B2
       (key[31]), .ZN (n_44));
  aoi22d1 g2275__6417(.A1 (n_36), .A2 (key[16]), .B1 (n_704_BAR), .B2
       (key[32]), .ZN (n_43));
  aoi22d1 g2276__5477(.A1 (n_34), .A2 (key[60]), .B1 (n_36), .B2
       (key[28]), .ZN (n_42));
  aoi22d1 g2277__2398(.A1 (n_36), .A2 (key[24]), .B1 (n_704_BAR), .B2
       (key[40]), .ZN (n_41));
  nr02d1 g2278__5107(.A1 (buffer), .A2 (reset), .ZN (n_40));
  inv0d1 g2279(.I (n_39), .ZN (n_38));
  aoim22d1 g2280__6260(.A1 (n_76), .A2 (j_cur[2]), .B1 (n_74), .B2
       (j_cur[1]), .Z (n_39));
  an12d1 g2282__4319(.A1 (n_33), .A2 (j_cur[1]), .Z (n_704_BAR));
  inv0d1 g2283(.I (n_37), .ZN (n_36));
  inv0d1 g2284(.I (n_75), .ZN (n_34));
  nd12d1 g2285__8428(.A1 (n_74), .A2 (j_cur[1]), .ZN (n_37));
  nr02d2 g2286__5526(.A1 (n_33), .A2 (j_cur[1]), .ZN (n_35));
  nd12d1 g2287__6783(.A1 (n_76), .A2 (j_cur[2]), .ZN (n_75));
  nr02d1 g2288__3680(.A1 (n_26), .A2 (reset), .ZN (n_32));
  nd12d1 g2289__1617(.A1 (j_cur[2]), .A2 (j_cur[0]), .ZN (n_33));
  or02d1 g2290__2802(.A1 (j_cur[0]), .A2 (j_cur[2]), .Z (n_74));
  or02d1 g2291__1705(.A1 (j_cur[1]), .A2 (j_cur[0]), .Z (n_76));
  inv0d0 g2292(.I (key[56]), .ZN (n_31));
  inv0d0 g2293(.I (key[18]), .ZN (n_30));
  inv0d0 g2294(.I (key_from_key[12]), .ZN (n_29));
  inv0d0 g2295(.I (key_from_key[5]), .ZN (n_28));
  inv0d0 g2296(.I (key[23]), .ZN (n_27));
  inv0d0 g2297(.I (start), .ZN (n_26));
  inv0d0 g2298(.I (key[20]), .ZN (n_25));
  inv0d0 g2299(.I (key_from_key[11]), .ZN (n_24));
  inv0d0 g2300(.I (key[48]), .ZN (n_23));
  inv0d0 g2301(.I (key[54]), .ZN (n_22));
  inv0d0 g2302(.I (key_from_key[13]), .ZN (n_21));
  inv0d0 g2303(.I (key_from_key[15]), .ZN (n_20));
  inv0d0 g2304(.I (key_from_key[3]), .ZN (n_19));
  inv0d0 g2305(.I (key[49]), .ZN (n_18));
  inv0d0 g2306(.I (key[25]), .ZN (n_17));
  dfnrq1 \j_cur_reg[2] (.CP (clk), .D (n_226), .Q (j_cur[2]));
  nr02d1 g1322__5122(.A1 (reset), .A2 (n_12), .ZN (n_14));
  aoi21d1 g1325__7098(.A (n_6), .B1 (n_9), .B2 (n_76), .ZN (n_12));
  oan211d1 g1326__6131(.A (reset), .B (n_8), .C1 (n_7), .C2 (j_cur[1]),
       .ZN (n_11));
  aoi321d1 g1327__1881(.A (n_704_BAR), .B1 (n_227), .B2 (j_cur[2]), .C1
       (j_cur[1]), .C2 (j_cur[0]), .C3 (n_77), .ZN (n_10));
  oai31d1 g1328__5115(.A (n_74), .B1 (n_4), .B2 (n_3), .B3 (n_2), .ZN
       (n_9));
  nd02d1 g1329__7482(.A1 (n_7), .A2 (j_cur[1]), .ZN (n_8));
  nd02d1 g1330__4733(.A1 (j_cur[0]), .A2 (n_4), .ZN (n_7));
  aoi21d1 g1331__6161(.A (j_cur[0]), .B1 (n_75), .B2 (n_77), .ZN (n_6));
  nd02d1 g1333__9945(.A1 (j_cur[2]), .A2 (n_77), .ZN (n_4));
  nr02d0 g2(.A1 (reset), .A2 (n_10), .ZN (n_226));
  oai21d1 g2319(.A (j_cur[0]), .B1 (j_cur[1]), .B2 (n_77), .ZN (n_227));
  dfnrb1 \j_cur_reg[0] (.CP (clk), .D (n_14), .Q (j_cur[0]), .QN (n_3));
  dfnrb1 \j_cur_reg[1] (.CP (clk), .D (n_11), .Q (j_cur[1]), .QN (n_2));
endmodule

module Top(clk_pad, reset_pad, key_pad, Plaintxt_pad, start_pad,
     cipher_pad, done_final_pad);
  input clk_pad, reset_pad, start_pad;
  input [7:0] key_pad;
  input [3:0] Plaintxt_pad;
  output [3:0] cipher_pad;
  output done_final_pad;
  wire clk_pad, reset_pad, start_pad;
  wire [7:0] key_pad;
  wire [3:0] Plaintxt_pad;
  wire [3:0] cipher_pad;
  wire done_final_pad;
  wire [3:0] Plaintxt;
  wire [7:0] key;
  wire [3:0] cipher;
  wire [31:0] data_from_input;
  wire [63:0] key_out_from_input;
  wire [31:0] cipher_from_simon;
  wire CLK, clk, done_final, input_done, n_0, reset, simon_done, start;
  input_taker_5 u_input_taker(.clk (clk), .reset (n_0), .key (key),
       .Plaintxt (Plaintxt), .start (start), .data (data_from_input),
       .key_out (key_out_from_input), .done (input_done));
  output_giver_N32_M4_C8 u_output_giver(.clk (clk), .reset (reset),
       .start (simon_done), .data (cipher_from_simon), .cipher
       (cipher), .done (done_final));
  simon_newer u_simon(.clk (clk), .reset (reset), .start (input_done),
       .key (key_out_from_input), .plain_text (data_from_input),
       .cipher_text (cipher_from_simon), .done (simon_done));
  pc3c01 CLK_3CPAD(.CCLK (CLK), .CP (clk));
  pc3d01 CLK_3DPAD(.PAD (clk_pad), .CIN (CLK));
  pc3o05 DONE_PAD(.I (done_final), .PAD (done_final_pad));
  pc3d01 INPUT_0_PAD(.PAD (Plaintxt_pad[0]), .CIN (Plaintxt[0]));
  pc3d01 INPUT_1_PAD(.PAD (Plaintxt_pad[1]), .CIN (Plaintxt[1]));
  pc3d01 INPUT_2_PAD(.PAD (Plaintxt_pad[2]), .CIN (Plaintxt[2]));
  pc3d01 INPUT_3_PAD(.PAD (Plaintxt_pad[3]), .CIN (Plaintxt[3]));
  pc3d01 KEY_0_PAD(.PAD (key_pad[0]), .CIN (key[0]));
  pc3d01 KEY_1_PAD(.PAD (key_pad[1]), .CIN (key[1]));
  pc3d01 KEY_2_PAD(.PAD (key_pad[2]), .CIN (key[2]));
  pc3d01 KEY_3_PAD(.PAD (key_pad[3]), .CIN (key[3]));
  pc3d01 KEY_4_PAD(.PAD (key_pad[4]), .CIN (key[4]));
  pc3d01 KEY_5_PAD(.PAD (key_pad[5]), .CIN (key[5]));
  pc3d01 KEY_6_PAD(.PAD (key_pad[6]), .CIN (key[6]));
  pc3d01 KEY_7_PAD(.PAD (key_pad[7]), .CIN (key[7]));
  pc3o05 OUTPUT_0_PAD(.I (cipher[0]), .PAD (cipher_pad[0]));
  pc3o05 OUTPUT_1_PAD(.I (cipher[1]), .PAD (cipher_pad[1]));
  pc3o05 OUTPUT_2_PAD(.I (cipher[2]), .PAD (cipher_pad[2]));
  pc3o05 OUTPUT_3_PAD(.I (cipher[3]), .PAD (cipher_pad[3]));
  pc3d01 RST_PAD(.PAD (reset_pad), .CIN (reset));
  pc3d01 START_PAD(.PAD (start_pad), .CIN (start));
  bufbdf g1(.I (reset), .Z (n_0));
endmodule

